services:
  build:
    image: alpine
    volumes:
      - .:/workspace
      - ./out:/out
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    env_file:
      - .env
    deploy:
      replicas: 1
    command:
      - sh
      - -c
      - |
        if ! command -v docker &> /dev/null; then
          apk add --no-cache docker-cli
        fi &&
        apk add --no-cache docker-cli-buildx &&
        docker buildx inspect builder >/dev/null 2>&1 || docker buildx create --name builder &&
        echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin &&
        docker buildx use builder &&
        #docker buildx build --no-cache --platform linux/amd64,linux/arm64 --push -t ${DOCKER_USERNAME}/${IMAGE_NAME}:latest --network=host . &&
        docker buildx build --no-cache --platform linux/arm64 --push -t ${DOCKER_USERNAME}/${IMAGE_NAME}:latest --network=host . &&
        echo 'Image pushed to Docker Hub successfully' &&
        echo 'Note: Please ensure the repository is set to public in Docker Hub web interface if needed'
