[package]
name = "kms"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
aws-config = "1.8"
aws-sdk-kms = "1.84"
aes-gcm = "0.10"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
tokio = { version = "1", features = ["full"] }