/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbortTransferInstruction {
    #[serde(rename = "abort_kind")]
    pub abort_kind: AbortKind,
    #[serde(rename = "transfer_instruction_cid")]
    pub transfer_instruction_cid: String,
}

impl AbortTransferInstruction {
    pub fn new(abort_kind: AbortKind, transfer_instruction_cid: String) -> AbortTransferInstruction {
        AbortTransferInstruction {
            abort_kind,
            transfer_instruction_cid,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AbortKind {
    #[serde(rename = "withdraw")]
    Withdraw,
    #[serde(rename = "reject")]
    Reject,
}

impl Default for AbortKind {
    fn default() -> AbortKind {
        Self::Withdraw
    }
}

