/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcsResponse {
    /// The same `record_time` as in the request.
    #[serde(rename = "record_time")]
    pub record_time: String,
    /// The same `migration_id` as in the request.
    #[serde(rename = "migration_id")]
    pub migration_id: i64,
    /// Up to `page_size` contracts in the ACS. `create_arguments` are always encoded as `compact_json`. 
    #[serde(rename = "created_events")]
    pub created_events: Vec<models::CreatedEvent>,
    /// When requesting the next page of results, pass this as `after` to the `AcsRequest` or `HoldingsStateRequest`. Will be absent when there are no more pages. 
    #[serde(rename = "next_page_token", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<i64>,
}

impl AcsResponse {
    pub fn new(record_time: String, migration_id: i64, created_events: Vec<models::CreatedEvent>) -> AcsResponse {
        AcsResponse {
            record_time,
            migration_id,
            created_events,
            next_page_token: None,
        }
    }
}

