/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AcsRequest {
    /// The migration id for which to return the ACS. 
    #[serde(rename = "migration_id")]
    pub migration_id: i64,
    /// The timestamp at which the contract set was active.  This needs to be an exact timestamp, i.e., needs to correspond to a timestamp reported by `/v0/state/acs/snapshot-timestamp` if `record_time_match` is set to `exact` (which is the default). If `record_time_match` is set to `at_or_before`, this can be any timestamp, and the most recent snapshot at or before the given `record_time` will be returned. 
    #[serde(rename = "record_time")]
    pub record_time: String,
    /// How to match the record_time. \"exact\" requires the record_time to match exactly. \"at_or_before\" finds the most recent snapshot at or before the given record_time. 
    #[serde(rename = "record_time_match", skip_serializing_if = "Option::is_none")]
    pub record_time_match: Option<RecordTimeMatch>,
    /// Pagination token for the next page of results. For this to be valid, this must be the `next_page_token` from a prior request with identical parameters aside from `after` and `page_size`; the response may be invalid otherwise. 
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<i64>,
    /// The maximum number of created events returned for this request. 
    #[serde(rename = "page_size")]
    pub page_size: i32,
    /// Filters the ACS by contracts in which these party IDs are stakeholders. 
    #[serde(rename = "party_ids", skip_serializing_if = "Option::is_none")]
    pub party_ids: Option<Vec<String>>,
    /// Filters the ACS by contracts with these template IDs, specified as \"PACKAGE_NAME:MODULE_NAME:ENTITY_NAME\". 
    #[serde(rename = "templates", skip_serializing_if = "Option::is_none")]
    pub templates: Option<Vec<String>>,
}

impl AcsRequest {
    pub fn new(migration_id: i64, record_time: String, page_size: i32) -> AcsRequest {
        AcsRequest {
            migration_id,
            record_time,
            record_time_match: None,
            after: None,
            page_size,
            party_ids: None,
            templates: None,
        }
    }
}
/// How to match the record_time. \"exact\" requires the record_time to match exactly. \"at_or_before\" finds the most recent snapshot at or before the given record_time. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecordTimeMatch {
    #[serde(rename = "exact")]
    Exact,
    #[serde(rename = "at_or_before")]
    AtOrBefore,
}

impl Default for RecordTimeMatch {
    fn default() -> RecordTimeMatch {
        Self::Exact
    }
}

