/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmuletAmount {
    /// The party that owns the amulet. 
    #[serde(rename = "amulet_owner")]
    pub amulet_owner: String,
    /// The amulet amount. 
    #[serde(rename = "amulet_amount")]
    pub amulet_amount: String,
}

impl AmuletAmount {
    pub fn new(amulet_owner: String, amulet_amount: String) -> AmuletAmount {
        AmuletAmount {
            amulet_owner,
            amulet_amount,
        }
    }
}

