/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnsEntry {
    /// If present, Daml contract ID of template `Splice.Ans:AnsEntry`. If absent, this is a DSO-provided entry for either the DSO or an SV. 
    #[serde(rename = "contract_id", skip_serializing_if = "Option::is_none")]
    pub contract_id: Option<String>,
    /// Owner party ID of this ANS entry.
    #[serde(rename = "user")]
    pub user: String,
    /// The ANS entry name.
    #[serde(rename = "name")]
    pub name: String,
    /// Either empty, or an http/https URL supplied by the `user`.
    #[serde(rename = "url")]
    pub url: String,
    /// Arbitrary description text supplied by `user`; may be empty.
    #[serde(rename = "description")]
    pub description: String,
    /// Time after which this ANS entry expires; if renewed, it will have a new `contract_id` and `expires_at`. If `null` or absent, does not expire; this is the case only for special entries provided by the DSO. 
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
}

impl AnsEntry {
    pub fn new(user: String, name: String, url: String, description: String) -> AnsEntry {
        AnsEntry {
            contract_id: None,
            user,
            name,
            url,
            description,
            expires_at: None,
        }
    }
}

