/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BalanceChange {
    /// The party for which the balance changes. 
    #[serde(rename = "party")]
    pub party: String,
    /// The change to the total balance introduced by this balance change, normalized to round zero, i.e., a amulet created in round 3 is treated as a amulet created in round 0 with a higher initial amount. 
    #[serde(rename = "change_to_initial_amount_as_of_round_zero")]
    pub change_to_initial_amount_as_of_round_zero: String,
    /// The change of total holding fees introduced by this balance change. 
    #[serde(rename = "change_to_holding_fees_rate")]
    pub change_to_holding_fees_rate: String,
}

impl BalanceChange {
    pub fn new(party: String, change_to_initial_amount_as_of_round_zero: String, change_to_holding_fees_rate: String) -> BalanceChange {
        BalanceChange {
            party,
            change_to_initial_amount_as_of_round_zero,
            change_to_holding_fees_rate,
        }
    }
}

