/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchListVotesByVoteRequestsRequest {
    /// Contract IDs of Daml template `Splice.DsoRules:VoteRequest`.
    #[serde(rename = "vote_request_contract_ids")]
    pub vote_request_contract_ids: Vec<String>,
}

impl BatchListVotesByVoteRequestsRequest {
    pub fn new(vote_request_contract_ids: Vec<String>) -> BatchListVotesByVoteRequestsRequest {
        BatchListVotesByVoteRequestsRequest {
            vote_request_contract_ids,
        }
    }
}

