/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckAndUpdateValidatorTrafficBalanceResponse {
    #[serde(rename = "approved")]
    pub approved: bool,
}

impl CheckAndUpdateValidatorTrafficBalanceResponse {
    pub fn new(approved: bool) -> CheckAndUpdateValidatorTrafficBalanceResponse {
        CheckAndUpdateValidatorTrafficBalanceResponse {
            approved,
        }
    }
}

