/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contract {
    #[serde(rename = "template_id")]
    pub template_id: String,
    #[serde(rename = "contract_id")]
    pub contract_id: String,
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
    #[serde(rename = "created_event_blob")]
    pub created_event_blob: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Contract {
    pub fn new(template_id: String, contract_id: String, payload: serde_json::Value, created_event_blob: String, created_at: String) -> Contract {
        Contract {
            template_id,
            contract_id,
            payload,
            created_event_blob,
            created_at,
        }
    }
}

