/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractWithState {
    #[serde(rename = "contract")]
    pub contract: Box<models::Contract>,
    #[serde(rename = "domain_id", skip_serializing_if = "Option::is_none")]
    pub domain_id: Option<String>,
}

impl ContractWithState {
    pub fn new(contract: models::Contract) -> ContractWithState {
        ContractWithState {
            contract: Box::new(contract),
            domain_id: None,
        }
    }
}

