/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatedEvent {
    #[serde(rename = "event_type")]
    pub event_type: String,
    /// The ID of this particular event. Equal to the key of this element of the containing `events_by_id` if this is part of a `TreeEvent`. 
    #[serde(rename = "event_id")]
    pub event_id: String,
    /// The ID of the created contract. 
    #[serde(rename = "contract_id")]
    pub contract_id: String,
    /// The template of the created contract. 
    #[serde(rename = "template_id")]
    pub template_id: String,
    /// The package name of the created contract. 
    #[serde(rename = "package_name")]
    pub package_name: String,
    /// The arguments that have been used to create the contract, in the form of JSON representation of a Daml record. 
    #[serde(rename = "create_arguments")]
    pub create_arguments: serde_json::Value,
    /// Ledger effective time of the transaction that created the contract. 
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Signatories to the contract, in the form of party IDs. 
    #[serde(rename = "signatories")]
    pub signatories: Vec<String>,
    /// Observers to the contract, in the form of party IDs. 
    #[serde(rename = "observers")]
    pub observers: Vec<String>,
}

impl CreatedEvent {
    pub fn new(event_type: String, event_id: String, contract_id: String, template_id: String, package_name: String, create_arguments: serde_json::Value, created_at: String, signatories: Vec<String>, observers: Vec<String>) -> CreatedEvent {
        CreatedEvent {
            event_type,
            event_id,
            contract_id,
            template_id,
            package_name,
            create_arguments,
            created_at,
            signatories,
            observers,
        }
    }
}

