/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DamlValueEncoding : How daml values should be encoded in the response. \"compact_json\" is a compact, human-readable JSON encoding. It is the same encoding as the one used in the HTTP JSON API or the JavaScript codegen. \"protobuf_json\" is a verbose JSON encoding that is more difficult to parse, but contains type information, i.e., the values can be parsed losslessly without having access to the Daml source code. Optional and defaults to \"compact_json\". 
/// How daml values should be encoded in the response. \"compact_json\" is a compact, human-readable JSON encoding. It is the same encoding as the one used in the HTTP JSON API or the JavaScript codegen. \"protobuf_json\" is a verbose JSON encoding that is more difficult to parse, but contains type information, i.e., the values can be parsed losslessly without having access to the Daml source code. Optional and defaults to \"compact_json\". 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DamlValueEncoding {
    #[serde(rename = "compact_json")]
    CompactJson,
    #[serde(rename = "protobuf_json")]
    ProtobufJson,

}

impl std::fmt::Display for DamlValueEncoding {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CompactJson => write!(f, "compact_json"),
            Self::ProtobufJson => write!(f, "protobuf_json"),
        }
    }
}

impl Default for DamlValueEncoding {
    fn default() -> DamlValueEncoding {
        Self::CompactJson
    }
}

