/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DomainSequencers {
    /// the synchronizer ID for the associated sequencers
    #[serde(rename = "domainId")]
    pub domain_id: String,
    /// the sequencers associated with the synchronizer
    #[serde(rename = "sequencers")]
    pub sequencers: Vec<models::DsoSequencer>,
}

impl DomainSequencers {
    pub fn new(domain_id: String, sequencers: Vec<models::DsoSequencer>) -> DomainSequencers {
        DomainSequencers {
            domain_id,
            sequencers,
        }
    }
}

