/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DsoSequencer {
    /// The synchronizer migration id corresponding to this sequencer. 
    #[serde(rename = "migrationId")]
    pub migration_id: i64,
    /// The id of the sequencer.
    #[serde(rename = "id")]
    pub id: String,
    /// The public accessible url of the sequencer.
    #[serde(rename = "url")]
    pub url: String,
    /// The sequencer's operating SV name.
    #[serde(rename = "svName")]
    pub sv_name: String,
    /// Any participant should subscribe to this sequencer after this time. 
    #[serde(rename = "availableAfter")]
    pub available_after: String,
}

impl DsoSequencer {
    pub fn new(migration_id: i64, id: String, url: String, sv_name: String, available_after: String) -> DsoSequencer {
        DsoSequencer {
            migration_id,
            id,
            url,
            sv_name,
            available_after,
        }
    }
}

