/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureSupportResponse {
    #[serde(rename = "no_holding_fees_on_transfers")]
    pub no_holding_fees_on_transfers: bool,
}

impl FeatureSupportResponse {
    pub fn new(no_holding_fees_on_transfers: bool) -> FeatureSupportResponse {
        FeatureSupportResponse {
            no_holding_fees_on_transfers,
        }
    }
}

