/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDsoInfoResponse {
    /// User ID representing the SV
    #[serde(rename = "sv_user")]
    pub sv_user: String,
    /// Party representing the SV
    #[serde(rename = "sv_party_id")]
    pub sv_party_id: String,
    /// Party representing the whole DSO; for Scan only, also returned by `/v0/dso-party-id` 
    #[serde(rename = "dso_party_id")]
    pub dso_party_id: String,
    /// Threshold required to pass vote requests; also known as the \"governance threshold\", it is always derived from the number of `svs` in `dso_rules` 
    #[serde(rename = "voting_threshold")]
    pub voting_threshold: i32,
    #[serde(rename = "latest_mining_round")]
    pub latest_mining_round: Box<models::ContractWithState>,
    #[serde(rename = "amulet_rules")]
    pub amulet_rules: Box<models::ContractWithState>,
    #[serde(rename = "dso_rules")]
    pub dso_rules: Box<models::ContractWithState>,
    /// For every one of `svs` listed in `dso_rules`, a contract of the Daml template `Splice.DSO.SvState.SvNodeState`. This does not include states for offboarded SVs, though they may still have an on-ledger state contract 
    #[serde(rename = "sv_node_states")]
    pub sv_node_states: Vec<models::ContractWithState>,
    /// Initial round from which the network bootstraps 
    #[serde(rename = "initial_round", skip_serializing_if = "Option::is_none")]
    pub initial_round: Option<String>,
}

impl GetDsoInfoResponse {
    pub fn new(sv_user: String, sv_party_id: String, dso_party_id: String, voting_threshold: i32, latest_mining_round: models::ContractWithState, amulet_rules: models::ContractWithState, dso_rules: models::ContractWithState, sv_node_states: Vec<models::ContractWithState>) -> GetDsoInfoResponse {
        GetDsoInfoResponse {
            sv_user,
            sv_party_id,
            dso_party_id,
            voting_threshold,
            latest_mining_round: Box::new(latest_mining_round),
            amulet_rules: Box::new(amulet_rules),
            dso_rules: Box::new(dso_rules),
            sv_node_states,
            initial_round: None,
        }
    }
}

