/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRoundOfLatestDataResponse {
    #[serde(rename = "round")]
    pub round: i64,
    #[serde(rename = "effectiveAt")]
    pub effective_at: String,
}

impl GetRoundOfLatestDataResponse {
    pub fn new(round: i64, effective_at: String) -> GetRoundOfLatestDataResponse {
        GetRoundOfLatestDataResponse {
            round,
            effective_at,
        }
    }
}

