/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOpenAndIssuingMiningRoundsRequest {
    /// The contract IDs for `open_mining_rounds` in the response the caller knows about. If unsure, an empty array is fine; only a performance penalty is incurred. 
    #[serde(rename = "cached_open_mining_round_contract_ids")]
    pub cached_open_mining_round_contract_ids: Vec<String>,
    /// The contract IDs for `issuing_mining_rounds` in the response the caller knows about. If unsure, an empty array is fine; only a performance penalty is incurred. 
    #[serde(rename = "cached_issuing_round_contract_ids")]
    pub cached_issuing_round_contract_ids: Vec<String>,
}

impl GetOpenAndIssuingMiningRoundsRequest {
    pub fn new(cached_open_mining_round_contract_ids: Vec<String>, cached_issuing_round_contract_ids: Vec<String>) -> GetOpenAndIssuingMiningRoundsRequest {
        GetOpenAndIssuingMiningRoundsRequest {
            cached_open_mining_round_contract_ids,
            cached_issuing_round_contract_ids,
        }
    }
}

