/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMemberTrafficStatusResponse {
    #[serde(rename = "traffic_status")]
    pub traffic_status: Box<models::MemberTrafficStatus>,
}

impl GetMemberTrafficStatusResponse {
    pub fn new(traffic_status: models::MemberTrafficStatus) -> GetMemberTrafficStatusResponse {
        GetMemberTrafficStatusResponse {
            traffic_status: Box::new(traffic_status),
        }
    }
}

