/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetTopValidatorsByValidatorFaucetsResponse {
    /// Up to `limit` validators, sorted greatest number of rounds collected first 
    #[serde(rename = "validatorsByReceivedFaucets")]
    pub validators_by_received_faucets: Vec<models::ValidatorReceivedFaucets>,
}

impl GetTopValidatorsByValidatorFaucetsResponse {
    pub fn new(validators_by_received_faucets: Vec<models::ValidatorReceivedFaucets>) -> GetTopValidatorsByValidatorFaucetsResponse {
        GetTopValidatorsByValidatorFaucetsResponse {
            validators_by_received_faucets,
        }
    }
}

