/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAmuletRulesResponse : Contract of the Daml template `Splice.AmuletRules.AmuletRules`, including the full schedule of `AmuletConfig` changes approved by the DSO. Callers should not assume that `initialValue` is up-to-date, and should instead search `futureValues` for the latest configuration valid as of now. `contract` will be absent if its ID matches the input `cached_amulet_rules_contract_id`. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAmuletRulesResponse {
    #[serde(rename = "amulet_rules_update")]
    pub amulet_rules_update: Box<models::MaybeCachedContractWithState>,
}

impl GetAmuletRulesResponse {
    /// Contract of the Daml template `Splice.AmuletRules.AmuletRules`, including the full schedule of `AmuletConfig` changes approved by the DSO. Callers should not assume that `initialValue` is up-to-date, and should instead search `futureValues` for the latest configuration valid as of now. `contract` will be absent if its ID matches the input `cached_amulet_rules_contract_id`. 
    pub fn new(amulet_rules_update: models::MaybeCachedContractWithState) -> GetAmuletRulesResponse {
        GetAmuletRulesResponse {
            amulet_rules_update: Box::new(amulet_rules_update),
        }
    }
}

