/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPartyToParticipantResponse {
    /// ID of the participant hosting the provided party, in the form `PAR::id::fingerprint` 
    #[serde(rename = "participant_id")]
    pub participant_id: String,
}

impl GetPartyToParticipantResponse {
    pub fn new(participant_id: String) -> GetPartyToParticipantResponse {
        GetPartyToParticipantResponse {
            participant_id,
        }
    }
}

