/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetOpenAndIssuingMiningRoundsResponse : Daml contracts of the templates `Splice.Round.OpenMiningRound` and `Splice.Round.IssuingMiningRound` representing rounds for which rewards can be registered or are currently being computed, respectively. Contract IDs in the input serve as input sets for the two `MaybeCachedContractWithStateMap`s as described for that structure for `open_mining_rounds` and `issuing_mining_rounds`. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetOpenAndIssuingMiningRoundsResponse {
    /// Suggested cache TTL for the response; this should expire before the `opensAt` of any open rounds that may not be in this response yet. 
    #[serde(rename = "time_to_live_in_microseconds")]
    pub time_to_live_in_microseconds: i32,
    /// Always created with respect to an input set of contract IDs. If an input contract ID is absent from the keys of this map, that contract should be considered removed by the caller; if present, `contract` may be empty, reflecting that the caller should already have the full contract data for that contract ID. Contracts not present in the input set will have full contract data. `domain_id` is always up-to-date; if undefined the contract is currently unassigned to a synchronizer, i.e. \"in-flight\". 
    #[serde(rename = "open_mining_rounds")]
    pub open_mining_rounds: std::collections::HashMap<String, models::MaybeCachedContractWithState>,
    /// Always created with respect to an input set of contract IDs. If an input contract ID is absent from the keys of this map, that contract should be considered removed by the caller; if present, `contract` may be empty, reflecting that the caller should already have the full contract data for that contract ID. Contracts not present in the input set will have full contract data. `domain_id` is always up-to-date; if undefined the contract is currently unassigned to a synchronizer, i.e. \"in-flight\". 
    #[serde(rename = "issuing_mining_rounds")]
    pub issuing_mining_rounds: std::collections::HashMap<String, models::MaybeCachedContractWithState>,
}

impl GetOpenAndIssuingMiningRoundsResponse {
    /// Daml contracts of the templates `Splice.Round.OpenMiningRound` and `Splice.Round.IssuingMiningRound` representing rounds for which rewards can be registered or are currently being computed, respectively. Contract IDs in the input serve as input sets for the two `MaybeCachedContractWithStateMap`s as described for that structure for `open_mining_rounds` and `issuing_mining_rounds`. 
    pub fn new(time_to_live_in_microseconds: i32, open_mining_rounds: std::collections::HashMap<String, models::MaybeCachedContractWithState>, issuing_mining_rounds: std::collections::HashMap<String, models::MaybeCachedContractWithState>) -> GetOpenAndIssuingMiningRoundsResponse {
        GetOpenAndIssuingMiningRoundsResponse {
            time_to_live_in_microseconds,
            open_mining_rounds,
            issuing_mining_rounds,
        }
    }
}

