/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetExternalPartyAmuletRulesResponse : A contract state update of Daml template `Splice.ExternalPartyAmuletRules.ExternalPartyAmuletRules` 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetExternalPartyAmuletRulesResponse {
    #[serde(rename = "external_party_amulet_rules_update")]
    pub external_party_amulet_rules_update: Box<models::MaybeCachedContractWithState>,
}

impl GetExternalPartyAmuletRulesResponse {
    /// A contract state update of Daml template `Splice.ExternalPartyAmuletRules.ExternalPartyAmuletRules` 
    pub fn new(external_party_amulet_rules_update: models::MaybeCachedContractWithState) -> GetExternalPartyAmuletRulesResponse {
        GetExternalPartyAmuletRulesResponse {
            external_party_amulet_rules_update: Box::new(external_party_amulet_rules_update),
        }
    }
}

