/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBackfillingStatusResponse {
    /// True if ALL backfilling processes are complete, false otherwise.  Some scan endpoints return error responses if backfilling is not complete (e.g., `/v1/updates`), others return partial results (e.g., `/v0/transactions`). This endpoint is a simple indicator for whether historical information may be incomplete.  To determine the progress of individual backfilling processes, inspect the corresponding metrics. 
    #[serde(rename = "complete")]
    pub complete: bool,
}

impl GetBackfillingStatusResponse {
    pub fn new(complete: bool) -> GetBackfillingStatusResponse {
        GetBackfillingStatusResponse {
            complete,
        }
    }
}

