/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetValidatorFaucetsByValidatorResponse {
    /// Statistics for any party ID arguments found to have valid onboarding licenses; the order in the response is unrelated to argument order. 
    #[serde(rename = "validatorsReceivedFaucets")]
    pub validators_received_faucets: Vec<models::ValidatorReceivedFaucets>,
}

impl GetValidatorFaucetsByValidatorResponse {
    pub fn new(validators_received_faucets: Vec<models::ValidatorReceivedFaucets>) -> GetValidatorFaucetsByValidatorResponse {
        GetValidatorFaucetsByValidatorResponse {
            validators_received_faucets,
        }
    }
}

