/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAmuletConfigForRoundResponse {
    #[serde(rename = "amulet_create_fee")]
    pub amulet_create_fee: String,
    #[serde(rename = "holding_fee")]
    pub holding_fee: String,
    #[serde(rename = "lock_holder_fee")]
    pub lock_holder_fee: String,
    #[serde(rename = "transfer_fee")]
    pub transfer_fee: Box<models::SteppedRate>,
}

impl GetAmuletConfigForRoundResponse {
    pub fn new(amulet_create_fee: String, holding_fee: String, lock_holder_fee: String, transfer_fee: models::SteppedRate) -> GetAmuletConfigForRoundResponse {
        GetAmuletConfigForRoundResponse {
            amulet_create_fee,
            holding_fee,
            lock_holder_fee,
            transfer_fee: Box::new(transfer_fee),
        }
    }
}

