/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetValidatorTrafficBalanceResponse {
    #[serde(rename = "remainingBalance")]
    pub remaining_balance: f64,
    #[serde(rename = "totalPurchased")]
    pub total_purchased: f64,
}

impl GetValidatorTrafficBalanceResponse {
    pub fn new(remaining_balance: f64, total_purchased: f64) -> GetValidatorTrafficBalanceResponse {
        GetValidatorTrafficBalanceResponse {
            remaining_balance,
            total_purchased,
        }
    }
}

