/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAnsRulesResponse : A contract state update of Daml template `Splice.Ans.AnsRules`. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAnsRulesResponse {
    #[serde(rename = "ans_rules_update")]
    pub ans_rules_update: Box<models::MaybeCachedContractWithState>,
}

impl GetAnsRulesResponse {
    /// A contract state update of Daml template `Splice.Ans.AnsRules`. 
    pub fn new(ans_rules_update: models::MaybeCachedContractWithState) -> GetAnsRulesResponse {
        GetAnsRulesResponse {
            ans_rules_update: Box::new(ans_rules_update),
        }
    }
}

