/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetImportUpdatesResponse {
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::UpdateHistoryItem>,
}

impl GetImportUpdatesResponse {
    pub fn new(transactions: Vec<models::UpdateHistoryItem>) -> GetImportUpdatesResponse {
        GetImportUpdatesResponse {
            transactions,
        }
    }
}

