/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUpdatesBeforeRequest {
    #[serde(rename = "migration_id")]
    pub migration_id: i64,
    #[serde(rename = "synchronizer_id")]
    pub synchronizer_id: String,
    /// Only return updates with a record time strictly smaller than this time. 
    #[serde(rename = "before")]
    pub before: String,
    /// Only return updates with a record time equal to or greater than this time. 
    #[serde(rename = "at_or_after", skip_serializing_if = "Option::is_none")]
    pub at_or_after: Option<String>,
    /// Return at most this many updates. The actual number of updates returned may be smaller. 
    #[serde(rename = "count")]
    pub count: i32,
}

impl GetUpdatesBeforeRequest {
    pub fn new(migration_id: i64, synchronizer_id: String, before: String, count: i32) -> GetUpdatesBeforeRequest {
        GetUpdatesBeforeRequest {
            migration_id,
            synchronizer_id,
            before,
            at_or_after: None,
            count,
        }
    }
}

