/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAcsSnapshotResponse {
    /// base64-encoded ACS snapshot for the intersection of the DSO party and the requested party’s ACS
    #[serde(rename = "acs_snapshot")]
    pub acs_snapshot: String,
}

impl GetAcsSnapshotResponse {
    pub fn new(acs_snapshot: String) -> GetAcsSnapshotResponse {
        GetAcsSnapshotResponse {
            acs_snapshot,
        }
    }
}

