/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSpliceInstanceNamesResponse {
    /// What to call this Splice network.
    #[serde(rename = "network_name")]
    pub network_name: String,
    /// URL of an HTML favicon for this Splice network.
    #[serde(rename = "network_favicon_url")]
    pub network_favicon_url: String,
    /// What this Splice network calls Amulet.
    #[serde(rename = "amulet_name")]
    pub amulet_name: String,
    /// The three-letter acronym for Amulet.
    #[serde(rename = "amulet_name_acronym")]
    pub amulet_name_acronym: String,
    /// What this Splice network calls the Amulet Name Service.
    #[serde(rename = "name_service_name")]
    pub name_service_name: String,
    /// The acronym for `name_service_name`.
    #[serde(rename = "name_service_name_acronym")]
    pub name_service_name_acronym: String,
}

impl GetSpliceInstanceNamesResponse {
    pub fn new(network_name: String, network_favicon_url: String, amulet_name: String, amulet_name_acronym: String, name_service_name: String, name_service_name_acronym: String) -> GetSpliceInstanceNamesResponse {
        GetSpliceInstanceNamesResponse {
            network_name,
            network_favicon_url,
            amulet_name,
            amulet_name_acronym,
            name_service_name,
            name_service_name_acronym,
        }
    }
}

