/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetWalletBalanceResponse {
    #[serde(rename = "wallet_balance")]
    pub wallet_balance: String,
}

impl GetWalletBalanceResponse {
    pub fn new(wallet_balance: String) -> GetWalletBalanceResponse {
        GetWalletBalanceResponse {
            wallet_balance,
        }
    }
}

