/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAnsRulesRequest {
    #[serde(rename = "cached_ans_rules_contract_id", skip_serializing_if = "Option::is_none")]
    pub cached_ans_rules_contract_id: Option<String>,
    #[serde(rename = "cached_ans_rules_domain_id", skip_serializing_if = "Option::is_none")]
    pub cached_ans_rules_domain_id: Option<String>,
}

impl GetAnsRulesRequest {
    pub fn new() -> GetAnsRulesRequest {
        GetAnsRulesRequest {
            cached_ans_rules_contract_id: None,
            cached_ans_rules_domain_id: None,
        }
    }
}

