/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HoldingsSummaryResponse {
    /// The same `record_time` as in the request.
    #[serde(rename = "record_time")]
    pub record_time: String,
    /// The same `migration_id` as in the request.
    #[serde(rename = "migration_id")]
    pub migration_id: i64,
    /// The same `as_of_round` as in the request, with the same default.
    #[serde(rename = "computed_as_of_round")]
    pub computed_as_of_round: i64,
    #[serde(rename = "summaries")]
    pub summaries: Vec<models::HoldingsSummary>,
}

impl HoldingsSummaryResponse {
    pub fn new(record_time: String, migration_id: i64, computed_as_of_round: i64, summaries: Vec<models::HoldingsSummary>) -> HoldingsSummaryResponse {
        HoldingsSummaryResponse {
            record_time,
            migration_id,
            computed_as_of_round,
            summaries,
        }
    }
}

