/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HoldingsSummary : Aggregate Amulet totals for a particular owner party ID.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HoldingsSummary {
    /// Owner party ID of the amulet. Guaranteed to be unique among `summaries`. 
    #[serde(rename = "party_id")]
    pub party_id: String,
    /// Sum of unlocked amulet at time of reception, not counting holding fees deducted since. 
    #[serde(rename = "total_unlocked_coin")]
    pub total_unlocked_coin: String,
    /// Sum of locked amulet at time of original amulet reception, not counting holding fees deducted since. 
    #[serde(rename = "total_locked_coin")]
    pub total_locked_coin: String,
    /// `total_unlocked_coin` + `total_locked_coin`. 
    #[serde(rename = "total_coin_holdings")]
    pub total_coin_holdings: String,
    /// Sum of holding fees as of `computed_as_of_round` that apply to unlocked amulet. 
    #[serde(rename = "accumulated_holding_fees_unlocked")]
    pub accumulated_holding_fees_unlocked: String,
    /// Sum of holding fees as of `computed_as_of_round` that apply to locked amulet, including fees applied since the amulet's creation round. 
    #[serde(rename = "accumulated_holding_fees_locked")]
    pub accumulated_holding_fees_locked: String,
    /// Same as `accumulated_holding_fees_unlocked` + `accumulated_holding_fees_locked`. 
    #[serde(rename = "accumulated_holding_fees_total")]
    pub accumulated_holding_fees_total: String,
    /// Same as `total_unlocked_coin` - `accumulated_holding_fees_unlocked`.
    #[serde(rename = "total_available_coin")]
    pub total_available_coin: String,
}

impl HoldingsSummary {
    /// Aggregate Amulet totals for a particular owner party ID.
    pub fn new(party_id: String, total_unlocked_coin: String, total_locked_coin: String, total_coin_holdings: String, accumulated_holding_fees_unlocked: String, accumulated_holding_fees_locked: String, accumulated_holding_fees_total: String, total_available_coin: String) -> HoldingsSummary {
        HoldingsSummary {
            party_id,
            total_unlocked_coin,
            total_locked_coin,
            total_coin_holdings,
            accumulated_holding_fees_unlocked,
            accumulated_holding_fees_locked,
            accumulated_holding_fees_total,
            total_available_coin,
        }
    }
}

