/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HoldingsSummaryRequest {
    /// The migration id for which to return the summary. 
    #[serde(rename = "migration_id")]
    pub migration_id: i64,
    /// The timestamp at which the contract set was active.  This needs to be an exact timestamp, i.e., needs to correspond to a timestamp reported by `/v0/state/acs/snapshot-timestamp` if `record_time_match` is set to `exact` (which is the default). If `record_time_match` is set to `at_or_before`, this can be any timestamp, and the most recent snapshot at or before the given `record_time` will be returned. 
    #[serde(rename = "record_time")]
    pub record_time: String,
    /// How to match the record_time. \"exact\" requires the record_time to match exactly. \"at_or_before\" finds the most recent snapshot at or before the given record_time. 
    #[serde(rename = "record_time_match", skip_serializing_if = "Option::is_none")]
    pub record_time_match: Option<RecordTimeMatch>,
    /// The owners for which to compute the summary. 
    #[serde(rename = "owner_party_ids")]
    pub owner_party_ids: Vec<String>,
    /// Compute holding fees as of this round. Defaults to the earliest open mining round. 
    #[serde(rename = "as_of_round", skip_serializing_if = "Option::is_none")]
    pub as_of_round: Option<i64>,
}

impl HoldingsSummaryRequest {
    pub fn new(migration_id: i64, record_time: String, owner_party_ids: Vec<String>) -> HoldingsSummaryRequest {
        HoldingsSummaryRequest {
            migration_id,
            record_time,
            record_time_match: None,
            owner_party_ids,
            as_of_round: None,
        }
    }
}
/// How to match the record_time. \"exact\" requires the record_time to match exactly. \"at_or_before\" finds the most recent snapshot at or before the given record_time. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecordTimeMatch {
    #[serde(rename = "exact")]
    Exact,
    #[serde(rename = "at_or_before")]
    AtOrBefore,
}

impl Default for RecordTimeMatch {
    fn default() -> RecordTimeMatch {
        Self::Exact
    }
}

