/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListAmuletPriceVotesResponse : Contracts of Daml template `Splice.DSO:AmuletPrice:AmuletPriceVote`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListAmuletPriceVotesResponse {
    #[serde(rename = "amulet_price_votes")]
    pub amulet_price_votes: Vec<models::Contract>,
}

impl ListAmuletPriceVotesResponse {
    /// Contracts of Daml template `Splice.DSO:AmuletPrice:AmuletPriceVote`.
    pub fn new(amulet_price_votes: Vec<models::Contract>) -> ListAmuletPriceVotesResponse {
        ListAmuletPriceVotesResponse {
            amulet_price_votes,
        }
    }
}

