/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListRoundTotalsRequest {
    #[serde(rename = "start_round")]
    pub start_round: i64,
    #[serde(rename = "end_round")]
    pub end_round: i64,
}

impl ListRoundTotalsRequest {
    pub fn new(start_round: i64, end_round: i64) -> ListRoundTotalsRequest {
        ListRoundTotalsRequest {
            start_round,
            end_round,
        }
    }
}

