/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListFeaturedAppRightsResponse : Contracts of Daml template `Splice.Amulet.FeaturedAppRight`. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListFeaturedAppRightsResponse {
    #[serde(rename = "featured_apps")]
    pub featured_apps: Vec<models::Contract>,
}

impl ListFeaturedAppRightsResponse {
    /// Contracts of Daml template `Splice.Amulet.FeaturedAppRight`. 
    pub fn new(featured_apps: Vec<models::Contract>) -> ListFeaturedAppRightsResponse {
        ListFeaturedAppRightsResponse {
            featured_apps,
        }
    }
}

