/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ListDsoRulesVoteRequestsResponse : Contracts of Daml template `Splice.DsoRules:VoteRequest`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListDsoRulesVoteRequestsResponse {
    #[serde(rename = "dso_rules_vote_requests")]
    pub dso_rules_vote_requests: Vec<models::Contract>,
}

impl ListDsoRulesVoteRequestsResponse {
    /// Contracts of Daml template `Splice.DsoRules:VoteRequest`.
    pub fn new(dso_rules_vote_requests: Vec<models::Contract>) -> ListDsoRulesVoteRequestsResponse {
        ListDsoRulesVoteRequestsResponse {
            dso_rules_vote_requests,
        }
    }
}

