/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListVoteRequestByTrackingCidResponse {
    /// Contracts of Daml template `Splice.DsoRules:VoteRequest` that match `vote_request_contract_ids` in the request. 
    #[serde(rename = "vote_requests")]
    pub vote_requests: Vec<models::Contract>,
}

impl ListVoteRequestByTrackingCidResponse {
    pub fn new(vote_requests: Vec<models::Contract>) -> ListVoteRequestByTrackingCidResponse {
        ListVoteRequestByTrackingCidResponse {
            vote_requests,
        }
    }
}

