/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListActivityRequest {
    /// Minimal event_id for returned activities. Note that all activities carry some monotonically-increasing event_id. begin_after_id sets the minimum value for event_id's for the query. 
    #[serde(rename = "begin_after_id", skip_serializing_if = "Option::is_none")]
    pub begin_after_id: Option<String>,
    /// The maximum number of activity items returned for this request. 
    #[serde(rename = "page_size")]
    pub page_size: i64,
}

impl ListActivityRequest {
    pub fn new(page_size: i64) -> ListActivityRequest {
        ListActivityRequest {
            begin_after_id: None,
            page_size,
        }
    }
}

