/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LookupTransferPreapprovalByPartyResponse : A Daml contract of template `Splice.AmuletRules:TransferPreapproval`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LookupTransferPreapprovalByPartyResponse {
    #[serde(rename = "transfer_preapproval")]
    pub transfer_preapproval: Box<models::ContractWithState>,
}

impl LookupTransferPreapprovalByPartyResponse {
    /// A Daml contract of template `Splice.AmuletRules:TransferPreapproval`.
    pub fn new(transfer_preapproval: models::ContractWithState) -> LookupTransferPreapprovalByPartyResponse {
        LookupTransferPreapprovalByPartyResponse {
            transfer_preapproval: Box::new(transfer_preapproval),
        }
    }
}

