/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LookupFeaturedAppRightResponse : If defined, a contract of Daml template `Splice.Amulet.FeaturedAppRight`. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LookupFeaturedAppRightResponse {
    #[serde(rename = "featured_app_right", skip_serializing_if = "Option::is_none")]
    pub featured_app_right: Option<Box<models::Contract>>,
}

impl LookupFeaturedAppRightResponse {
    /// If defined, a contract of Daml template `Splice.Amulet.FeaturedAppRight`. 
    pub fn new() -> LookupFeaturedAppRightResponse {
        LookupFeaturedAppRightResponse {
            featured_app_right: None,
        }
    }
}

