/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LookupTransferCommandCounterByPartyResponse : A Daml contract of template `Splice.ExternalPartyAmuletRules:TransferCommandCounter`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LookupTransferCommandCounterByPartyResponse {
    #[serde(rename = "transfer_command_counter")]
    pub transfer_command_counter: Box<models::ContractWithState>,
}

impl LookupTransferCommandCounterByPartyResponse {
    /// A Daml contract of template `Splice.ExternalPartyAmuletRules:TransferCommandCounter`.
    pub fn new(transfer_command_counter: models::ContractWithState) -> LookupTransferCommandCounterByPartyResponse {
        LookupTransferCommandCounterByPartyResponse {
            transfer_command_counter: Box::new(transfer_command_counter),
        }
    }
}

