/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MigrationSchedule {
    #[serde(rename = "time")]
    pub time: String,
    #[serde(rename = "migration_id")]
    pub migration_id: i64,
}

impl MigrationSchedule {
    pub fn new(time: String, migration_id: i64) -> MigrationSchedule {
        MigrationSchedule {
            time,
            migration_id,
        }
    }
}

