/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotInitializedStatusResponse {
    #[serde(rename = "not_initialized")]
    pub not_initialized: Box<models::NotInitialized>,
}

impl NotInitializedStatusResponse {
    pub fn new(not_initialized: models::NotInitialized) -> NotInitializedStatusResponse {
        NotInitializedStatusResponse {
            not_initialized: Box::new(not_initialized),
        }
    }
}

