/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartyAndRewards {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "rewards")]
    pub rewards: String,
}

impl PartyAndRewards {
    pub fn new(provider: String, rewards: String) -> PartyAndRewards {
        PartyAndRewards {
            provider,
            rewards,
        }
    }
}

