/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateStep {
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "rate")]
    pub rate: String,
}

impl RateStep {
    pub fn new(amount: String, rate: String) -> RateStep {
        RateStep {
            amount,
            rate,
        }
    }
}

