/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiverAmount {
    /// The receiver who will own the created output amulet. 
    #[serde(rename = "party")]
    pub party: String,
    /// The amount of amulet to receive, before deducting receiver's part of the fees. 
    #[serde(rename = "amount")]
    pub amount: String,
    /// Total fees paid by the receiver, based on receiver_fee_ratio on outputs 
    #[serde(rename = "receiver_fee")]
    pub receiver_fee: String,
}

impl ReceiverAmount {
    pub fn new(party: String, amount: String, receiver_fee: String) -> ReceiverAmount {
        ReceiverAmount {
            party,
            amount,
            receiver_fee,
        }
    }
}

