/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordTimeRange {
    #[serde(rename = "synchronizer_id")]
    pub synchronizer_id: String,
    #[serde(rename = "min")]
    pub min: String,
    #[serde(rename = "max")]
    pub max: String,
}

impl RecordTimeRange {
    pub fn new(synchronizer_id: String, min: String, max: String) -> RecordTimeRange {
        RecordTimeRange {
            synchronizer_id,
            min,
            max,
        }
    }
}

