/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoundPartyTotals {
    #[serde(rename = "closed_round")]
    pub closed_round: i64,
    #[serde(rename = "party")]
    pub party: String,
    #[serde(rename = "app_rewards")]
    pub app_rewards: String,
    #[serde(rename = "validator_rewards")]
    pub validator_rewards: String,
    #[serde(rename = "traffic_purchased")]
    pub traffic_purchased: i64,
    #[serde(rename = "traffic_purchased_cc_spent")]
    pub traffic_purchased_cc_spent: String,
    #[serde(rename = "traffic_num_purchases")]
    pub traffic_num_purchases: i64,
    #[serde(rename = "cumulative_app_rewards")]
    pub cumulative_app_rewards: String,
    #[serde(rename = "cumulative_validator_rewards")]
    pub cumulative_validator_rewards: String,
    #[serde(rename = "cumulative_change_to_initial_amount_as_of_round_zero")]
    pub cumulative_change_to_initial_amount_as_of_round_zero: String,
    #[serde(rename = "cumulative_change_to_holding_fees_rate")]
    pub cumulative_change_to_holding_fees_rate: String,
    #[serde(rename = "cumulative_traffic_purchased")]
    pub cumulative_traffic_purchased: i64,
    #[serde(rename = "cumulative_traffic_purchased_cc_spent")]
    pub cumulative_traffic_purchased_cc_spent: String,
    #[serde(rename = "cumulative_traffic_num_purchases")]
    pub cumulative_traffic_num_purchases: i64,
}

impl RoundPartyTotals {
    pub fn new(closed_round: i64, party: String, app_rewards: String, validator_rewards: String, traffic_purchased: i64, traffic_purchased_cc_spent: String, traffic_num_purchases: i64, cumulative_app_rewards: String, cumulative_validator_rewards: String, cumulative_change_to_initial_amount_as_of_round_zero: String, cumulative_change_to_holding_fees_rate: String, cumulative_traffic_purchased: i64, cumulative_traffic_purchased_cc_spent: String, cumulative_traffic_num_purchases: i64) -> RoundPartyTotals {
        RoundPartyTotals {
            closed_round,
            party,
            app_rewards,
            validator_rewards,
            traffic_purchased,
            traffic_purchased_cc_spent,
            traffic_num_purchases,
            cumulative_app_rewards,
            cumulative_validator_rewards,
            cumulative_change_to_initial_amount_as_of_round_zero,
            cumulative_change_to_holding_fees_rate,
            cumulative_traffic_purchased,
            cumulative_traffic_purchased_cc_spent,
            cumulative_traffic_num_purchases,
        }
    }
}

