/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScanInfo {
    /// The public accessible url of the scan.
    #[serde(rename = "publicUrl")]
    pub public_url: String,
    /// The sequencer's operating SV name.
    #[serde(rename = "svName")]
    pub sv_name: String,
}

impl ScanInfo {
    pub fn new(public_url: String, sv_name: String) -> ScanInfo {
        ScanInfo {
            public_url,
            sv_name,
        }
    }
}

