/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SenderAmount {
    /// The sender who has transferred amulet. 
    #[serde(rename = "party")]
    pub party: String,
    /// Total amount of amulet input into this transfer, before deducting holding fees. 
    #[serde(rename = "input_amulet_amount", skip_serializing_if = "Option::is_none")]
    pub input_amulet_amount: Option<String>,
    /// Total amount of app rewards input into this transfer. 
    #[serde(rename = "input_app_reward_amount", skip_serializing_if = "Option::is_none")]
    pub input_app_reward_amount: Option<String>,
    /// Total amount of validator rewards input into this transfer. 
    #[serde(rename = "input_validator_reward_amount", skip_serializing_if = "Option::is_none")]
    pub input_validator_reward_amount: Option<String>,
    /// Total amount of sv rewards input into this transfer. 
    #[serde(rename = "input_sv_reward_amount", skip_serializing_if = "Option::is_none")]
    pub input_sv_reward_amount: Option<String>,
    /// Total amount of validator faucet coupon issuance input into this transfer. 
    #[serde(rename = "input_validator_faucet_amount", skip_serializing_if = "Option::is_none")]
    pub input_validator_faucet_amount: Option<String>,
    /// Fee charged for returning change to the sender, which is the smaller of the left-over balance after paying for all outputs or one amulet create fee. 
    #[serde(rename = "sender_change_fee")]
    pub sender_change_fee: String,
    /// The final amount of amulet returned to the sender after paying for all outputs and fees. 
    #[serde(rename = "sender_change_amount")]
    pub sender_change_amount: String,
    /// Total fees paid by the sender, based on receiver's receiver_fee_ratio on outputs 
    #[serde(rename = "sender_fee")]
    pub sender_fee: String,
    /// Holding fees paid by the sender on their input amulets. 
    #[serde(rename = "holding_fees")]
    pub holding_fees: String,
}

impl SenderAmount {
    pub fn new(party: String, sender_change_fee: String, sender_change_amount: String, sender_fee: String, holding_fees: String) -> SenderAmount {
        SenderAmount {
            party,
            input_amulet_amount: None,
            input_app_reward_amount: None,
            input_validator_reward_amount: None,
            input_sv_reward_amount: None,
            input_validator_faucet_amount: None,
            sender_change_fee,
            sender_change_amount,
            sender_fee,
            holding_fees,
        }
    }
}

