/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Status {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "uptime")]
    pub uptime: String,
    #[serde(rename = "ports")]
    pub ports: std::collections::HashMap<String, i32>,
    #[serde(rename = "extra", skip_serializing_if = "Option::is_none")]
    pub extra: Option<std::path::PathBuf>,
    #[serde(rename = "active")]
    pub active: bool,
}

impl Status {
    pub fn new(id: String, uptime: String, ports: std::collections::HashMap<String, i32>, active: bool) -> Status {
        Status {
            id,
            uptime,
            ports,
            extra: None,
            active,
        }
    }
}

