/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SteppedRate {
    #[serde(rename = "initial")]
    pub initial: String,
    #[serde(rename = "steps")]
    pub steps: Vec<models::RateStep>,
}

impl SteppedRate {
    pub fn new(initial: String, steps: Vec<models::RateStep>) -> SteppedRate {
        SteppedRate {
            initial,
            steps,
        }
    }
}

