/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SynchronizerBftSequencer {
    /// The synchronizer migration id corresponding to this sequencer. 
    #[serde(rename = "migrationId")]
    pub migration_id: i64,
    /// The id of the sequencer.
    #[serde(rename = "id")]
    pub id: String,
    /// The public accessible P2P url of the sequencer, use for inter sequencer communication.
    #[serde(rename = "p2pUrl")]
    pub p2p_url: String,
}

impl SynchronizerBftSequencer {
    pub fn new(migration_id: i64, id: String, p2p_url: String) -> SynchronizerBftSequencer {
        SynchronizerBftSequencer {
            migration_id,
            id,
            p2p_url,
        }
    }
}

