/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SynchronizerIdentities {
    #[serde(rename = "sequencer_id")]
    pub sequencer_id: String,
    #[serde(rename = "sequencer_identity_transactions")]
    pub sequencer_identity_transactions: Vec<String>,
    #[serde(rename = "mediator_id")]
    pub mediator_id: String,
    #[serde(rename = "mediator_identity_transactions")]
    pub mediator_identity_transactions: Vec<String>,
}

impl SynchronizerIdentities {
    pub fn new(sequencer_id: String, sequencer_identity_transactions: Vec<String>, mediator_id: String, mediator_identity_transactions: Vec<String>) -> SynchronizerIdentities {
        SynchronizerIdentities {
            sequencer_id,
            sequencer_identity_transactions,
            mediator_id,
            mediator_identity_transactions,
        }
    }
}

