/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SynchronizerBootstrappingTransactions {
    #[serde(rename = "domain_parameters")]
    pub domain_parameters: String,
    #[serde(rename = "sequencer_domain_state")]
    pub sequencer_domain_state: String,
    #[serde(rename = "mediator_domain_state")]
    pub mediator_domain_state: String,
}

impl SynchronizerBootstrappingTransactions {
    pub fn new(domain_parameters: String, sequencer_domain_state: String, mediator_domain_state: String) -> SynchronizerBootstrappingTransactions {
        SynchronizerBootstrappingTransactions {
            domain_parameters,
            sequencer_domain_state,
            mediator_domain_state,
        }
    }
}

