/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetMemberTrafficState {
    /// Total extra traffic purchased for the member on the given synchronizer in bytes. 
    #[serde(rename = "total_purchased")]
    pub total_purchased: i64,
}

impl TargetMemberTrafficState {
    pub fn new(total_purchased: i64) -> TargetMemberTrafficState {
        TargetMemberTrafficState {
            total_purchased,
        }
    }
}

