/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Transfer : A transfer between one sender and possibly many receivers, provided by an application provider. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transfer {
    /// The application provider. 
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "sender")]
    pub sender: Box<models::SenderAmount>,
    /// The amounts and fees per receiver. 
    #[serde(rename = "receivers")]
    pub receivers: Vec<models::ReceiverAmount>,
    /// Normalized balance changes per party caused by this transfer. 
    #[serde(rename = "balance_changes")]
    pub balance_changes: Vec<models::BalanceChange>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "transferInstructionReceiver", skip_serializing_if = "Option::is_none")]
    pub transfer_instruction_receiver: Option<String>,
    #[serde(rename = "transferInstructionAmount", skip_serializing_if = "Option::is_none")]
    pub transfer_instruction_amount: Option<String>,
    #[serde(rename = "transferInstructionCid", skip_serializing_if = "Option::is_none")]
    pub transfer_instruction_cid: Option<String>,
    #[serde(rename = "transfer_kind", skip_serializing_if = "Option::is_none")]
    pub transfer_kind: Option<TransferKind>,
}

impl Transfer {
    /// A transfer between one sender and possibly many receivers, provided by an application provider. 
    pub fn new(provider: String, sender: models::SenderAmount, receivers: Vec<models::ReceiverAmount>, balance_changes: Vec<models::BalanceChange>) -> Transfer {
        Transfer {
            provider,
            sender: Box::new(sender),
            receivers,
            balance_changes,
            description: None,
            transfer_instruction_receiver: None,
            transfer_instruction_amount: None,
            transfer_instruction_cid: None,
            transfer_kind: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferKind {
    #[serde(rename = "create_transfer_instruction")]
    CreateTransferInstruction,
    #[serde(rename = "transfer_instruction_accept")]
    TransferInstructionAccept,
    #[serde(rename = "preapproval_send")]
    PreapprovalSend,
}

impl Default for TransferKind {
    fn default() -> TransferKind {
        Self::CreateTransferInstruction
    }
}

