/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionViews {
    #[serde(rename = "views")]
    pub views: Vec<models::TransactionView>,
    #[serde(rename = "root_views")]
    pub root_views: Vec<i32>,
}

impl TransactionViews {
    pub fn new(views: Vec<models::TransactionView>, root_views: Vec<i32>) -> TransactionViews {
        TransactionViews {
            views,
            root_views,
        }
    }
}

