/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "status")]
pub enum TransferCommandContractStatus {
    #[serde(rename="created")]
    Created(Box<models::TransferCommandCreatedResponse>),
    #[serde(rename="sent")]
    Sent(Box<models::TransferCommandSentResponse>),
    #[serde(rename="failed")]
    Failed(Box<models::TransferCommandFailedResponse>),
}

impl Default for TransferCommandContractStatus {
    fn default() -> Self {
        Self::Created(Default::default())
    }
}

/// The reason for the failure of the TransferCommand. failed:   Completing the transfer failed, check the reason for details. withdrawn:   The sender has withdrawn the TransferCommand before it could be completed. expired:   The expiry time on the TransferCommand was reached before it could be completed. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FailureKind {
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "withdrawn")]
    Withdrawn,
}

impl Default for FailureKind {
    fn default() -> FailureKind {
        Self::Failed
    }
}

