/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionHistoryResponseItem {
    /// Describes the type of activity that occurred. Determines if the data for the transaction should be read from the `transfer`, `mint`, or `tap` property. 
    #[serde(rename = "transaction_type")]
    pub transaction_type: TransactionType,
    /// The event id. 
    #[serde(rename = "event_id")]
    pub event_id: String,
    /// The ledger offset of the event. Note that this field may not be the same across nodes, and therefore should not be compared between SVs. 
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<String>,
    /// The effective date of the event. 
    #[serde(rename = "date")]
    pub date: String,
    /// The id of the domain through which this transaction was sequenced. 
    #[serde(rename = "domain_id")]
    pub domain_id: String,
    /// The round for which this transaction was registered. 
    #[serde(rename = "round", skip_serializing_if = "Option::is_none")]
    pub round: Option<i64>,
    /// The amulet price for the round at which this transfer was executed. 
    #[serde(rename = "amulet_price", skip_serializing_if = "Option::is_none")]
    pub amulet_price: Option<String>,
    #[serde(rename = "transfer", skip_serializing_if = "Option::is_none")]
    pub transfer: Option<Box<models::Transfer>>,
    #[serde(rename = "mint", skip_serializing_if = "Option::is_none")]
    pub mint: Option<Box<models::AmuletAmount>>,
    #[serde(rename = "tap", skip_serializing_if = "Option::is_none")]
    pub tap: Option<Box<models::AmuletAmount>>,
    #[serde(rename = "abort_transfer_instruction", skip_serializing_if = "Option::is_none")]
    pub abort_transfer_instruction: Option<Box<models::AbortTransferInstruction>>,
}

impl TransactionHistoryResponseItem {
    pub fn new(transaction_type: TransactionType, event_id: String, date: String, domain_id: String) -> TransactionHistoryResponseItem {
        TransactionHistoryResponseItem {
            transaction_type,
            event_id,
            offset: None,
            date,
            domain_id,
            round: None,
            amulet_price: None,
            transfer: None,
            mint: None,
            tap: None,
            abort_transfer_instruction: None,
        }
    }
}
/// Describes the type of activity that occurred. Determines if the data for the transaction should be read from the `transfer`, `mint`, or `tap` property. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "transfer")]
    Transfer,
    #[serde(rename = "mint")]
    Mint,
    #[serde(rename = "devnet_tap")]
    DevnetTap,
    #[serde(rename = "abort_transfer_instruction")]
    AbortTransferInstruction,
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::Transfer
    }
}

