/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionHistoryRequest {
    /// Note that all transactions carry some monotonically-increasing event_id. Omit this page_end_event_id to start reading the first page, from the beginning or the end of the ledger, depending on the sort_order column. A subsequent request can fill the page_end_event_id with the last event_id of the TransactionHistoryResponse to continue reading in the same sort_order. The transaction with event_id == page_end_event_id will be skipped in the next response, making it possible to continuously read pages in the same sort_order. 
    #[serde(rename = "page_end_event_id", skip_serializing_if = "Option::is_none")]
    pub page_end_event_id: Option<String>,
    /// Sort order for the transactions. For ascending order, from beginning to the end of the ledger, use \"asc\". For descending order, from end to beginning of the ledger, use \"desc\". \"asc\" is used if the sort_order is omitted. 
    #[serde(rename = "sort_order", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<SortOrder>,
    /// The maximum number of transactions returned for this request. 
    #[serde(rename = "page_size")]
    pub page_size: i64,
}

impl TransactionHistoryRequest {
    pub fn new(page_size: i64) -> TransactionHistoryRequest {
        TransactionHistoryRequest {
            page_end_event_id: None,
            sort_order: None,
            page_size,
        }
    }
}
/// Sort order for the transactions. For ascending order, from beginning to the end of the ledger, use \"asc\". For descending order, from end to beginning of the ledger, use \"desc\". \"asc\" is used if the sort_order is omitted. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SortOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

impl Default for SortOrder {
    fn default() -> SortOrder {
        Self::Asc
    }
}

