/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionView {
    #[serde(rename = "view_id")]
    pub view_id: i32,
    #[serde(rename = "informees")]
    pub informees: Vec<String>,
    #[serde(rename = "confirming_parties")]
    pub confirming_parties: Vec<models::Quorum>,
    #[serde(rename = "sub_views")]
    pub sub_views: Vec<i32>,
}

impl TransactionView {
    pub fn new(view_id: i32, informees: Vec<String>, confirming_parties: Vec<models::Quorum>, sub_views: Vec<i32>) -> TransactionView {
        TransactionView {
            view_id,
            informees,
            confirming_parties,
            sub_views,
        }
    }
}

