/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferCommandFailedResponse {
    /// The status of the transfer command. created:   The transfer command has been created and is waiting for automation to complete it. sent:   The transfer command has been completed and the transfer to the receiver has finished. failed:   The transfer command has failed permanently and nothing has been transferred. Refer to   failure_reason for details. A new transfer command can be created. 
    #[serde(rename = "status")]
    pub status: String,
    /// The reason for the failure of the TransferCommand. failed:   Completing the transfer failed, check the reason for details. withdrawn:   The sender has withdrawn the TransferCommand before it could be completed. expired:   The expiry time on the TransferCommand was reached before it could be completed. 
    #[serde(rename = "failure_kind")]
    pub failure_kind: FailureKind,
    /// Human readable description of the failure 
    #[serde(rename = "reason")]
    pub reason: String,
}

impl TransferCommandFailedResponse {
    pub fn new(status: String, failure_kind: FailureKind, reason: String) -> TransferCommandFailedResponse {
        TransferCommandFailedResponse {
            status,
            failure_kind,
            reason,
        }
    }
}
/// The reason for the failure of the TransferCommand. failed:   Completing the transfer failed, check the reason for details. withdrawn:   The sender has withdrawn the TransferCommand before it could be completed. expired:   The expiry time on the TransferCommand was reached before it could be completed. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FailureKind {
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "withdrawn")]
    Withdrawn,
}

impl Default for FailureKind {
    fn default() -> FailureKind {
        Self::Failed
    }
}

