/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferCommandContractWithStatus : A contract of Daml template `Splice.ExternalPartyAmuletRules:TransferCommand`, and its status determined by the latest transactions. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferCommandContractWithStatus {
    #[serde(rename = "contract")]
    pub contract: Box<models::Contract>,
    #[serde(rename = "status")]
    pub status: Box<models::TransferCommandContractStatus>,
}

impl TransferCommandContractWithStatus {
    /// A contract of Daml template `Splice.ExternalPartyAmuletRules:TransferCommand`, and its status determined by the latest transactions. 
    pub fn new(contract: models::Contract, status: models::TransferCommandContractStatus) -> TransferCommandContractWithStatus {
        TransferCommandContractWithStatus {
            contract: Box::new(contract),
            status: Box::new(status),
        }
    }
}

