/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TreeEvent : Either a creation or an exercise of a contract. 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "event_type")]
pub enum TreeEvent {
    #[serde(rename="created_event")]
    CreatedEvent(Box<models::CreatedEvent>),
    #[serde(rename="exercised_event")]
    ExercisedEvent(Box<models::ExercisedEvent>),
}

impl Default for TreeEvent {
    fn default() -> Self {
        Self::CreatedEvent(Default::default())
    }
}


