/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateHistoryItem : An individual item in the update history. May be a transaction or a contract reassignment. 
/// An individual item in the update history. May be a transaction or a contract reassignment. 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateHistoryItem {
    UpdateHistoryTransaction(Box<models::UpdateHistoryTransaction>),
    UpdateHistoryReassignment(Box<models::UpdateHistoryReassignment>),
}

impl Default for UpdateHistoryItem {
    fn default() -> Self {
        Self::UpdateHistoryTransaction(Default::default())
    }
}

