/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateHistoryAssignment {
    /// The party ID who submitted this reassignment 
    #[serde(rename = "submitter")]
    pub submitter: String,
    /// The id of the synchronizer from which the contract was reassigned 
    #[serde(rename = "source_synchronizer")]
    pub source_synchronizer: String,
    /// The id of the synchronizer to which the contract was reassigned 
    #[serde(rename = "target_synchronizer")]
    pub target_synchronizer: String,
    /// The migration id of the target synchronizer 
    #[serde(rename = "migration_id")]
    pub migration_id: i64,
    /// The id of the corresponding unassign event; this assignment will usually, but not always, occur after the so-identified unassignment event. 
    #[serde(rename = "unassign_id")]
    pub unassign_id: String,
    #[serde(rename = "created_event")]
    pub created_event: Box<models::CreatedEvent>,
    /// Each corresponding assigned and unassigned event has the same reassignment_counter. This strictly increases with each unassign command for the same contract. Creation of the contract corresponds to reassignment_counter 0.
    #[serde(rename = "reassignment_counter")]
    pub reassignment_counter: i64,
}

impl UpdateHistoryAssignment {
    pub fn new(submitter: String, source_synchronizer: String, target_synchronizer: String, migration_id: i64, unassign_id: String, created_event: models::CreatedEvent, reassignment_counter: i64) -> UpdateHistoryAssignment {
        UpdateHistoryAssignment {
            submitter,
            source_synchronizer,
            target_synchronizer,
            migration_id,
            unassign_id,
            created_event: Box::new(created_event),
            reassignment_counter,
        }
    }
}

