/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateHistoryTransactionV2 {
    /// The id of the update. 
    #[serde(rename = "update_id")]
    pub update_id: String,
    /// The migration id of the synchronizer. 
    #[serde(rename = "migration_id")]
    pub migration_id: i64,
    /// This transaction's Daml workflow ID; a workflow ID can be associated with multiple transactions. If empty, no workflow ID was set. 
    #[serde(rename = "workflow_id")]
    pub workflow_id: String,
    /// The time at which the transaction was sequenced, with microsecond resolution, using ISO-8601 representation. 
    #[serde(rename = "record_time")]
    pub record_time: String,
    /// The id of the synchronizer through which this transaction was sequenced. 
    #[serde(rename = "synchronizer_id")]
    pub synchronizer_id: String,
    /// Ledger effective time, using ISO-8601 representation. This is the time returned by `getTime` for all Daml executed as part of this transaction, both by the submitting participant and all confirming participants. 
    #[serde(rename = "effective_at")]
    pub effective_at: String,
    /// Roots of the transaction tree. These are guaranteed to occur as keys of the `events_by_id` object. 
    #[serde(rename = "root_event_ids")]
    pub root_event_ids: Vec<String>,
    /// Changes to the ledger that were caused by this transaction, keyed by ID and sorted lexicographically by ID for display consistency. Values are nodes of the transaction tree. Within a transaction, IDs may be referenced by `root_event_ids` or `child_event_ids` in `ExercisedEvent` herein, which are sorted in the order as they occurred in the transaction. 
    #[serde(rename = "events_by_id")]
    pub events_by_id: std::collections::HashMap<String, models::TreeEvent>,
}

impl UpdateHistoryTransactionV2 {
    pub fn new(update_id: String, migration_id: i64, workflow_id: String, record_time: String, synchronizer_id: String, effective_at: String, root_event_ids: Vec<String>, events_by_id: std::collections::HashMap<String, models::TreeEvent>) -> UpdateHistoryTransactionV2 {
        UpdateHistoryTransactionV2 {
            update_id,
            migration_id,
            workflow_id,
            record_time,
            synchronizer_id,
            effective_at,
            root_event_ids,
            events_by_id,
        }
    }
}

