/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateHistoryReassignment : A contract reassignment between synchronizer. May be an assignment or unassignment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateHistoryReassignment {
    /// The id of the update. 
    #[serde(rename = "update_id")]
    pub update_id: String,
    /// The absolute offset. Note that this field may not be the same across nodes, and therefore should not be compared between SVs. 
    #[serde(rename = "offset")]
    pub offset: String,
    /// The time at which the transaction was sequenced. 
    #[serde(rename = "record_time")]
    pub record_time: String,
    #[serde(rename = "event")]
    pub event: Box<models::UpdateHistoryReassignmentEvent>,
}

impl UpdateHistoryReassignment {
    /// A contract reassignment between synchronizer. May be an assignment or unassignment.
    pub fn new(update_id: String, offset: String, record_time: String, event: models::UpdateHistoryReassignmentEvent) -> UpdateHistoryReassignment {
        UpdateHistoryReassignment {
            update_id,
            offset,
            record_time,
            event: Box::new(event),
        }
    }
}

