/*
 * Scan API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidatorPurchasedTraffic {
    #[serde(rename = "validator")]
    pub validator: String,
    #[serde(rename = "numPurchases")]
    pub num_purchases: i64,
    #[serde(rename = "totalTrafficPurchased")]
    pub total_traffic_purchased: i64,
    #[serde(rename = "totalCcSpent")]
    pub total_cc_spent: String,
    #[serde(rename = "lastPurchasedInRound")]
    pub last_purchased_in_round: i64,
}

impl ValidatorPurchasedTraffic {
    pub fn new(validator: String, num_purchases: i64, total_traffic_purchased: i64, total_cc_spent: String, last_purchased_in_round: i64) -> ValidatorPurchasedTraffic {
        ValidatorPurchasedTraffic {
            validator,
            num_purchases,
            total_traffic_purchased,
            total_cc_spent,
            last_purchased_in_round,
        }
    }
}

