/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocateExternalPartyResponse {
    /// 
    #[serde(rename = "partyId")]
    pub party_id: String,
}

impl AllocateExternalPartyResponse {
    pub fn new(party_id: String) -> AllocateExternalPartyResponse {
        AllocateExternalPartyResponse {
            party_id,
        }
    }
}

