/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocateExternalPartyRequest : Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)``
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocateExternalPartyRequest {
    /// TODO(#27670) support synchronizer aliases Synchronizer ID on which to onboard the party Required
    #[serde(rename = "synchronizer")]
    pub synchronizer: String,
    /// TopologyTransactions to onboard the external party Can contain: - A namespace for the party. This can be either a single NamespaceDelegation, or DecentralizedNamespaceDefinition along with its authorized namespace owners in the form of NamespaceDelegations. May be provided, if so it must be fully authorized by the signatures in this request combined with the existing topology state. - A PartyToKeyMapping to register the party's signing keys. May be provided, if so it must be fully authorized by the signatures in this request combined with the existing topology state. - A PartyToParticipant to register the hosting relationship of the party. Must be provided. Required
    #[serde(rename = "onboardingTransactions", skip_serializing_if = "Option::is_none")]
    pub onboarding_transactions: Option<Vec<models::SignedTransaction>>,
    /// Optional signatures of the combined hash of all onboarding_transactions This may be used instead of providing signatures on each individual transaction
    #[serde(rename = "multiHashSignatures", skip_serializing_if = "Option::is_none")]
    pub multi_hash_signatures: Option<Vec<models::Signature>>,
    /// The id of the ``Identity Provider`` If not set, assume the party is managed by the default identity provider. Optional
    #[serde(rename = "identityProviderId")]
    pub identity_provider_id: String,
}

impl AllocateExternalPartyRequest {
    /// Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)``
    pub fn new(synchronizer: String, identity_provider_id: String) -> AllocateExternalPartyRequest {
        AllocateExternalPartyRequest {
            synchronizer,
            onboarding_transactions: None,
            multi_hash_signatures: None,
            identity_provider_id,
        }
    }
}

