/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocatePartyRequest : Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)``
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocatePartyRequest {
    /// A hint to the participant which party ID to allocate. It can be ignored. Must be a valid PartyIdString (as described in ``value.proto``). Optional
    #[serde(rename = "partyIdHint")]
    pub party_id_hint: String,
    #[serde(rename = "localMetadata", skip_serializing_if = "Option::is_none")]
    pub local_metadata: Option<Box<models::ObjectMeta>>,
    /// The id of the ``Identity Provider`` Optional, if not set, assume the party is managed by the default identity provider or party is not hosted by the participant.
    #[serde(rename = "identityProviderId")]
    pub identity_provider_id: String,
    /// The synchronizer, on which the party should be allocated. For backwards compatibility, this field may be omitted, if the participant is connected to only one synchronizer. Otherwise a synchronizer must be specified. Optional
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
    /// The user who will get the act_as rights to the newly allocated party. If set to an empty string (the default), no user will get rights to the party. Optional
    #[serde(rename = "userId")]
    pub user_id: String,
}

impl AllocatePartyRequest {
    /// Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)``
    pub fn new(party_id_hint: String, identity_provider_id: String, synchronizer_id: String, user_id: String) -> AllocatePartyRequest {
        AllocatePartyRequest {
            party_id_hint,
            local_metadata: None,
            identity_provider_id,
            synchronizer_id,
            user_id,
        }
    }
}

