/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CostEstimation : Estimation of the cost of submitting the prepared transaction The estimation is done against the synchronizer chosen during preparation of the transaction (or the one explicitly requested). The cost of re-assigning contracts to another synchronizer when necessary is not included in the estimation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CostEstimation {
    /// Timestamp at which the estimation was made
    #[serde(rename = "estimationTimestamp", skip_serializing_if = "Option::is_none")]
    pub estimation_timestamp: Option<String>,
    /// Estimated traffic cost of the confirmation request associated with the transaction
    #[serde(rename = "confirmationRequestTrafficCostEstimation")]
    pub confirmation_request_traffic_cost_estimation: i64,
    /// Estimated traffic cost of the confirmation response associated with the transaction This field can also be used as an indication of the cost that other potential confirming nodes of the party will incur to approve or reject the transaction
    #[serde(rename = "confirmationResponseTrafficCostEstimation")]
    pub confirmation_response_traffic_cost_estimation: i64,
    /// Sum of the fields above
    #[serde(rename = "totalTrafficCostEstimation")]
    pub total_traffic_cost_estimation: i64,
}

impl CostEstimation {
    /// Estimation of the cost of submitting the prepared transaction The estimation is done against the synchronizer chosen during preparation of the transaction (or the one explicitly requested). The cost of re-assigning contracts to another synchronizer when necessary is not included in the estimation.
    pub fn new(confirmation_request_traffic_cost_estimation: i64, confirmation_response_traffic_cost_estimation: i64, total_traffic_cost_estimation: i64) -> CostEstimation {
        CostEstimation {
            estimation_timestamp: None,
            confirmation_request_traffic_cost_estimation,
            confirmation_response_traffic_cost_estimation,
            total_traffic_cost_estimation,
        }
    }
}

