/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CostEstimationHints : Hints to improve cost estimation precision of a prepared transaction
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CostEstimationHints {
    /// Disable cost estimation Default (not set) is false
    #[serde(rename = "disabled")]
    pub disabled: bool,
    /// Details on the keys that will be used to sign the transaction (how many and of which type). Signature size impacts the cost of the transaction. If empty, the signature sizes will be approximated with threshold-many signatures (where threshold is defined in the PartyToKeyMapping of the external party), using keys in the order they are registered. Optional (empty list is equivalent to not providing this field)
    #[serde(rename = "expectedSignatures", skip_serializing_if = "Option::is_none")]
    pub expected_signatures: Option<Vec<ExpectedSignatures>>,
}

impl CostEstimationHints {
    /// Hints to improve cost estimation precision of a prepared transaction
    pub fn new(disabled: bool) -> CostEstimationHints {
        CostEstimationHints {
            disabled,
            expected_signatures: None,
        }
    }
}
/// Details on the keys that will be used to sign the transaction (how many and of which type). Signature size impacts the cost of the transaction. If empty, the signature sizes will be approximated with threshold-many signatures (where threshold is defined in the PartyToKeyMapping of the external party), using keys in the order they are registered. Optional (empty list is equivalent to not providing this field)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExpectedSignatures {
    #[serde(rename = "SIGNING_ALGORITHM_SPEC_UNSPECIFIED")]
    SigningAlgorithmSpecUnspecified,
    #[serde(rename = "SIGNING_ALGORITHM_SPEC_ED25519")]
    SigningAlgorithmSpecEd25519,
    #[serde(rename = "SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_256")]
    SigningAlgorithmSpecEcDsaSha256,
    #[serde(rename = "SIGNING_ALGORITHM_SPEC_EC_DSA_SHA_384")]
    SigningAlgorithmSpecEcDsaSha384,
}

impl Default for ExpectedSignatures {
    fn default() -> ExpectedSignatures {
        Self::SigningAlgorithmSpecUnspecified
    }
}

