/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeduplicationPeriod1 : The actual deduplication window used for the submission, which is derived from ``Commands.deduplication_period``. The ledger may convert the deduplication period into other descriptions and extend the period in implementation-specified ways.  Used to audit the deduplication guarantee described in ``commands.proto``.  Optional; the deduplication guarantee applies even if the completion omits this field.
/// The actual deduplication window used for the submission, which is derived from ``Commands.deduplication_period``. The ledger may convert the deduplication period into other descriptions and extend the period in implementation-specified ways.  Used to audit the deduplication guarantee described in ``commands.proto``.  Optional; the deduplication guarantee applies even if the completion omits this field.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeduplicationPeriod1 {
    DeduplicationPeriod1OneOf(Box<models::DeduplicationPeriod1OneOf>),
    DeduplicationPeriod1OneOf1(Box<models::DeduplicationPeriod1OneOf1>),
    DeduplicationPeriod1OneOf2(Box<models::DeduplicationPeriod1OneOf2>),
}

impl Default for DeduplicationPeriod1 {
    fn default() -> Self {
        Self::DeduplicationPeriod1OneOf(Default::default())
    }
}

