/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateExternalPartyTopologyRequest {
    /// TODO(#27670) support synchronizer aliases Required: synchronizer-id for which we are building this request.
    #[serde(rename = "synchronizer")]
    pub synchronizer: String,
    /// Required: the actual party id will be constructed from this hint and a fingerprint of the public key
    #[serde(rename = "partyHint")]
    pub party_hint: String,
    #[serde(rename = "publicKey", skip_serializing_if = "Option::is_none")]
    pub public_key: Option<Box<models::SigningPublicKey>>,
    /// Optional: if true, then the local participant will only be observing, not confirming. Default false.
    #[serde(rename = "localParticipantObservationOnly")]
    pub local_participant_observation_only: bool,
    /// Optional: other participant ids which should be confirming for this party
    #[serde(rename = "otherConfirmingParticipantUids", skip_serializing_if = "Option::is_none")]
    pub other_confirming_participant_uids: Option<Vec<String>>,
    /// Optional: Confirmation threshold >= 1 for the party. Defaults to all available confirmers (or if set to 0).
    #[serde(rename = "confirmationThreshold")]
    pub confirmation_threshold: i32,
    /// Optional: other observing participant ids for this party
    #[serde(rename = "observingParticipantUids", skip_serializing_if = "Option::is_none")]
    pub observing_participant_uids: Option<Vec<String>>,
}

impl GenerateExternalPartyTopologyRequest {
    pub fn new(synchronizer: String, party_hint: String, local_participant_observation_only: bool, confirmation_threshold: i32) -> GenerateExternalPartyTopologyRequest {
        GenerateExternalPartyTopologyRequest {
            synchronizer,
            party_hint,
            public_key: None,
            local_participant_observation_only,
            other_confirming_participant_uids: None,
            confirmation_threshold,
            observing_participant_uids: None,
        }
    }
}

