/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventsByContractIdRequest {
    /// The contract id being queried. Required
    #[serde(rename = "contractId")]
    pub contract_id: String,
    #[serde(rename = "eventFormat", skip_serializing_if = "Option::is_none")]
    pub event_format: Option<Box<models::EventFormat>>,
}

impl GetEventsByContractIdRequest {
    pub fn new(contract_id: String) -> GetEventsByContractIdRequest {
        GetEventsByContractIdRequest {
            contract_id,
            event_format: None,
        }
    }
}

