/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPreferredPackagesRequest {
    /// The package-name vetting requirements for which the preferred packages should be resolved.  Generally it is enough to provide the requirements for the intended command's root package-names. Additional package-name requirements can be provided when additional Daml transaction informees need to use package dependencies of the command's root packages.  Required
    #[serde(rename = "packageVettingRequirements", skip_serializing_if = "Option::is_none")]
    pub package_vetting_requirements: Option<Vec<models::PackageVettingRequirement>>,
    /// The synchronizer whose vetting state to use for resolving this query. If not specified, the vetting state of all the synchronizers the participant is connected to will be used. Optional
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
    /// The timestamp at which the package vetting validity should be computed on the latest topology snapshot as seen by the participant. If not provided, the participant's current clock time is used. Optional
    #[serde(rename = "vettingValidAt", skip_serializing_if = "Option::is_none")]
    pub vetting_valid_at: Option<String>,
}

impl GetPreferredPackagesRequest {
    pub fn new(synchronizer_id: String) -> GetPreferredPackagesRequest {
        GetPreferredPackagesRequest {
            package_vetting_requirements: None,
            synchronizer_id,
            vetting_valid_at: None,
        }
    }
}

