/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPackageStatusResponse {
    /// The status of the package.
    #[serde(rename = "packageStatus")]
    pub package_status: String,
}

impl GetPackageStatusResponse {
    pub fn new(package_status: String) -> GetPackageStatusResponse {
        GetPackageStatusResponse {
            package_status,
        }
    }
}

