/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsExecuteSubmissionRequest {
    /// the prepared transaction Typically this is the value of the `prepared_transaction` field in `PrepareSubmissionResponse` obtained from calling `prepareSubmission`. Required
    #[serde(rename = "preparedTransaction", skip_serializing_if = "Option::is_none")]
    pub prepared_transaction: Option<String>,
    #[serde(rename = "partySignatures", skip_serializing_if = "Option::is_none")]
    pub party_signatures: Option<Box<models::PartySignatures>>,
    #[serde(rename = "deduplicationPeriod")]
    pub deduplication_period: Box<models::DeduplicationPeriod2>,
    /// A unique identifier to distinguish completions for different submissions with the same change ID. Typically a random UUID. Applications are expected to use a different UUID for each retry of a submission with the same change ID. Must be a valid LedgerString (as described in ``value.proto``).  Required
    #[serde(rename = "submissionId")]
    pub submission_id: String,
    /// See [PrepareSubmissionRequest.user_id] Optional
    #[serde(rename = "userId")]
    pub user_id: String,
    /// The hashing scheme version used when building the hash Required
    #[serde(rename = "hashingSchemeVersion")]
    pub hashing_scheme_version: HashingSchemeVersion,
    #[serde(rename = "minLedgerTime", skip_serializing_if = "Option::is_none")]
    pub min_ledger_time: Option<Box<models::MinLedgerTime>>,
}

impl JsExecuteSubmissionRequest {
    pub fn new(deduplication_period: models::DeduplicationPeriod2, submission_id: String, user_id: String, hashing_scheme_version: HashingSchemeVersion) -> JsExecuteSubmissionRequest {
        JsExecuteSubmissionRequest {
            prepared_transaction: None,
            party_signatures: None,
            deduplication_period: Box::new(deduplication_period),
            submission_id,
            user_id,
            hashing_scheme_version,
            min_ledger_time: None,
        }
    }
}
/// The hashing scheme version used when building the hash Required
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HashingSchemeVersion {
    #[serde(rename = "HASHING_SCHEME_VERSION_UNSPECIFIED")]
    HashingSchemeVersionUnspecified,
    #[serde(rename = "HASHING_SCHEME_VERSION_V2")]
    HashingSchemeVersionV2,
}

impl Default for HashingSchemeVersion {
    fn default() -> HashingSchemeVersion {
        Self::HashingSchemeVersionUnspecified
    }
}

