/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsReassignmentEventOneOf {
    #[serde(rename = "JsAssignmentEvent")]
    pub js_assignment_event: Box<models::JsAssignmentEvent>,
}

impl JsReassignmentEventOneOf {
    pub fn new(js_assignment_event: models::JsAssignmentEvent) -> JsReassignmentEventOneOf {
        JsReassignmentEventOneOf {
            js_assignment_event: Box::new(js_assignment_event),
        }
    }
}

