/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KindOneOf7 {
    #[serde(rename = "ParticipantAdmin")]
    pub participant_admin: Box<models::ParticipantAdmin>,
}

impl KindOneOf7 {
    pub fn new(participant_admin: models::ParticipantAdmin) -> KindOneOf7 {
        KindOneOf7 {
            participant_admin: Box::new(participant_admin),
        }
    }
}

