/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KindOneOf3 {
    #[serde(rename = "CanReadAs")]
    pub can_read_as: Box<models::CanReadAs>,
}

impl KindOneOf3 {
    pub fn new(can_read_as: models::CanReadAs) -> KindOneOf3 {
        KindOneOf3 {
            can_read_as: Box::new(can_read_as),
        }
    }
}

