/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListVettedPackagesRequest {
    #[serde(rename = "packageMetadataFilter", skip_serializing_if = "Option::is_none")]
    pub package_metadata_filter: Option<Box<models::PackageMetadataFilter>>,
    #[serde(rename = "topologyStateFilter", skip_serializing_if = "Option::is_none")]
    pub topology_state_filter: Option<Box<models::TopologyStateFilter>>,
    /// Pagination token to determine the specific page to fetch. Using the token guarantees that ``VettedPackages`` on a subsequent page are all greater (``VettedPackages`` are sorted by synchronizer ID then participant ID) than the last ``VettedPackages`` on a previous page.  The server does not store intermediate results between calls chained by a series of page tokens. As a consequence, if new vetted packages are being added and a page is requested twice using the same token, more packages can be returned on the second call.  Leave unspecified (i.e. as empty string) to fetch the first page.  Optional
    #[serde(rename = "pageToken")]
    pub page_token: String,
    /// Maximum number of ``VettedPackages`` results to return in a single page.  If the page_size is unspecified (i.e. left as 0), the server will decide the number of results to be returned.  If the page_size exceeds the maximum supported by the server, an error will be returned.  To obtain the server's maximum consult the PackageService descriptor available in the VersionService.  Optional
    #[serde(rename = "pageSize")]
    pub page_size: i32,
}

impl ListVettedPackagesRequest {
    pub fn new(page_token: String, page_size: i32) -> ListVettedPackagesRequest {
        ListVettedPackagesRequest {
            package_metadata_filter: None,
            topology_state_filter: None,
            page_token,
            page_size,
        }
    }
}

