/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListVettedPackagesResponse {
    /// All ``VettedPackages`` that contain at least one ``VettedPackage`` matching both a ``PackageMetadataFilter`` and a ``TopologyStateFilter``. Sorted by synchronizer_id then participant_id.
    #[serde(rename = "vettedPackages", skip_serializing_if = "Option::is_none")]
    pub vetted_packages: Option<Vec<models::VettedPackages>>,
    /// Pagination token to retrieve the next page. Empty string if there are no further results.
    #[serde(rename = "nextPageToken")]
    pub next_page_token: String,
}

impl ListVettedPackagesResponse {
    pub fn new(next_page_token: String) -> ListVettedPackagesResponse {
        ListVettedPackagesResponse {
            vetted_packages: None,
            next_page_token,
        }
    }
}

