/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Operation {
    OperationOneOf(Box<models::OperationOneOf>),
    OperationOneOf1(Box<models::OperationOneOf1>),
    OperationOneOf2(Box<models::OperationOneOf2>),
}

impl Default for Operation {
    fn default() -> Self {
        Self::OperationOneOf(Default::default())
    }
}

