/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OperationOneOf2 {
    #[serde(rename = "Vet")]
    pub vet: Box<models::Vet>,
}

impl OperationOneOf2 {
    pub fn new(vet: models::Vet) -> OperationOneOf2 {
        OperationOneOf2 {
            vet: Box::new(vet),
        }
    }
}

