/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PackageVettingRequirement : Defines a package-name for which the commonly vetted package with the highest version must be found.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageVettingRequirement {
    /// The parties whose participants' vetting state should be considered when resolving the preferred package. Required
    #[serde(rename = "parties", skip_serializing_if = "Option::is_none")]
    pub parties: Option<Vec<String>>,
    /// The package-name for which the preferred package should be resolved. Required
    #[serde(rename = "packageName")]
    pub package_name: String,
}

impl PackageVettingRequirement {
    /// Defines a package-name for which the commonly vetted package with the highest version must be found.
    pub fn new(package_name: String) -> PackageVettingRequirement {
        PackageVettingRequirement {
            parties: None,
            package_name,
        }
    }
}

