/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageFeature {
    /// The maximum number of vetted packages the server can return in a single response (page) when listing them.
    #[serde(rename = "maxVettedPackagesPageSize")]
    pub max_vetted_packages_page_size: i32,
}

impl PackageFeature {
    pub fn new(max_vetted_packages_page_size: i32) -> PackageFeature {
        PackageFeature {
            max_vetted_packages_page_size,
        }
    }
}

