/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PackageMetadataFilter : Filter the VettedPackages by package metadata.  A PackageMetadataFilter without package_ids and without package_name_prefixes matches any vetted package.  Non-empty fields specify candidate values of which at least one must match. If both fields are set, then a candidate is returned if it matches one of the fields.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageMetadataFilter {
    /// If this list is non-empty, any vetted package with a package ID in this list will match the filter.
    #[serde(rename = "packageIds", skip_serializing_if = "Option::is_none")]
    pub package_ids: Option<Vec<String>>,
    /// If this list is non-empty, any vetted package with a name matching at least one prefix in this list will match the filter.
    #[serde(rename = "packageNamePrefixes", skip_serializing_if = "Option::is_none")]
    pub package_name_prefixes: Option<Vec<String>>,
}

impl PackageMetadataFilter {
    /// Filter the VettedPackages by package metadata.  A PackageMetadataFilter without package_ids and without package_name_prefixes matches any vetted package.  Non-empty fields specify candidate values of which at least one must match. If both fields are set, then a candidate is returned if it matches one of the fields.
    pub fn new() -> PackageMetadataFilter {
        PackageMetadataFilter {
            package_ids: None,
            package_name_prefixes: None,
        }
    }
}

