/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantAuthorizationRevoked {
    #[serde(rename = "value")]
    pub value: Box<models::ParticipantAuthorizationRevoked1>,
}

impl ParticipantAuthorizationRevoked {
    pub fn new(value: models::ParticipantAuthorizationRevoked1) -> ParticipantAuthorizationRevoked {
        ParticipantAuthorizationRevoked {
            value: Box::new(value),
        }
    }
}

