/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PriorTopologySerial : The serial of last ``VettedPackages`` topology transaction on a given participant and synchronizer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriorTopologySerial {
    #[serde(rename = "serial")]
    pub serial: Box<models::Serial>,
}

impl PriorTopologySerial {
    /// The serial of last ``VettedPackages`` topology transaction on a given participant and synchronizer.
    pub fn new(serial: models::Serial) -> PriorTopologySerial {
        PriorTopologySerial {
            serial: Box::new(serial),
        }
    }
}

