/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SerialOneOf2 {
    #[serde(rename = "Prior")]
    pub prior: Box<models::Prior>,
}

impl SerialOneOf2 {
    pub fn new(prior: models::Prior) -> SerialOneOf2 {
        SerialOneOf2 {
            prior: Box::new(prior),
        }
    }
}

