/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SerialOneOf1 {
    #[serde(rename = "NoPrior")]
    pub no_prior: serde_json::Value,
}

impl SerialOneOf1 {
    pub fn new(no_prior: serde_json::Value) -> SerialOneOf1 {
        SerialOneOf1 {
            no_prior,
        }
    }
}

