/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SigningPublicKey {
    /// The serialization format of the public key
    #[serde(rename = "format")]
    pub format: String,
    /// Serialized public key in the format specified above
    #[serde(rename = "keyData")]
    pub key_data: String,
    /// The key specification
    #[serde(rename = "keySpec")]
    pub key_spec: String,
}

impl SigningPublicKey {
    pub fn new(format: String, key_data: String, key_spec: String) -> SigningPublicKey {
        SigningPublicKey {
            format,
            key_data,
            key_spec,
        }
    }
}

