/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopologyEventEventOneOf3 {
    #[serde(rename = "ParticipantAuthorizationRevoked")]
    pub participant_authorization_revoked: Box<models::ParticipantAuthorizationRevoked>,
}

impl TopologyEventEventOneOf3 {
    pub fn new(participant_authorization_revoked: models::ParticipantAuthorizationRevoked) -> TopologyEventEventOneOf3 {
        TopologyEventEventOneOf3 {
            participant_authorization_revoked: Box::new(participant_authorization_revoked),
        }
    }
}

