/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopologyEventEventOneOf2 {
    #[serde(rename = "ParticipantAuthorizationChanged")]
    pub participant_authorization_changed: Box<models::ParticipantAuthorizationChanged>,
}

impl TopologyEventEventOneOf2 {
    pub fn new(participant_authorization_changed: models::ParticipantAuthorizationChanged) -> TopologyEventEventOneOf2 {
        TopologyEventEventOneOf2 {
            participant_authorization_changed: Box::new(participant_authorization_changed),
        }
    }
}

