/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TopologyEvent {
    TopologyEventOneOf(Box<models::TopologyEventOneOf>),
    TopologyEventOneOf1(Box<models::TopologyEventOneOf1>),
    TopologyEventOneOf2(Box<models::TopologyEventOneOf2>),
}

impl Default for TopologyEvent {
    fn default() -> Self {
        Self::TopologyEventOneOf(Default::default())
    }
}

