/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Unvet {
    #[serde(rename = "value")]
    pub value: Box<models::Unvet1>,
}

impl Unvet {
    pub fn new(value: models::Unvet1) -> Unvet {
        Unvet {
            value: Box::new(value),
        }
    }
}

