/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vet1 {
    #[serde(rename = "packages", skip_serializing_if = "Option::is_none")]
    pub packages: Option<Vec<models::VettedPackagesRef>>,
    #[serde(rename = "newValidFromInclusive", skip_serializing_if = "Option::is_none")]
    pub new_valid_from_inclusive: Option<String>,
    #[serde(rename = "newValidUntilExclusive", skip_serializing_if = "Option::is_none")]
    pub new_valid_until_exclusive: Option<String>,
}

impl Vet1 {
    pub fn new() -> Vet1 {
        Vet1 {
            packages: None,
            new_valid_from_inclusive: None,
            new_valid_until_exclusive: None,
        }
    }
}

