/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VettedPackages : The list of packages vetted on a given participant and synchronizer, modelled after ``VettedPackages`` in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_. The list only contains packages that matched a filter in the query that originated it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VettedPackages {
    /// Sorted by package_name and package_version where known, and package_id as a last resort.
    #[serde(rename = "packages", skip_serializing_if = "Option::is_none")]
    pub packages: Option<Vec<models::VettedPackage>>,
    /// Participant on which these packages are vetted. Always present.
    #[serde(rename = "participantId")]
    pub participant_id: String,
    /// Synchronizer on which these packages are vetted. Always present.
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
    /// Serial of last ``VettedPackages`` topology transaction of this participant and on this synchronizer. Always present.
    #[serde(rename = "topologySerial")]
    pub topology_serial: i32,
}

impl VettedPackages {
    /// The list of packages vetted on a given participant and synchronizer, modelled after ``VettedPackages`` in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_. The list only contains packages that matched a filter in the query that originated it.
    pub fn new(participant_id: String, synchronizer_id: String, topology_serial: i32) -> VettedPackages {
        VettedPackages {
            packages: None,
            participant_id,
            synchronizer_id,
            topology_serial,
        }
    }
}

