/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VettedPackagesRef : A reference to identify one or more packages.  A reference matches a package if its ``package_id`` matches the package's ID, its ``package_name`` matches the package's name, and its ``package_version`` matches the package's version. If an attribute in the reference is left unspecified (i.e. as an empty string), that attribute is treated as a wildcard. At a minimum, ``package_id`` or the ``package_name`` must be specified.  If a reference does not match any package, the reference is considered unresolved and the entire update request is rejected.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VettedPackagesRef {
    /// Package's package id must be the same as this field. Optional
    #[serde(rename = "packageId")]
    pub package_id: String,
    /// Package's name must be the same as this field. Optional
    #[serde(rename = "packageName")]
    pub package_name: String,
    /// Package's version must be the same as this field. Optional
    #[serde(rename = "packageVersion")]
    pub package_version: String,
}

impl VettedPackagesRef {
    /// A reference to identify one or more packages.  A reference matches a package if its ``package_id`` matches the package's ID, its ``package_name`` matches the package's name, and its ``package_version`` matches the package's version. If an attribute in the reference is left unspecified (i.e. as an empty string), that attribute is treated as a wildcard. At a minimum, ``package_id`` or the ``package_name`` must be specified.  If a reference does not match any package, the reference is considered unresolved and the entire update request is rejected.
    pub fn new(package_id: String, package_name: String, package_version: String) -> VettedPackagesRef {
        VettedPackagesRef {
            package_id,
            package_name,
            package_version,
        }
    }
}

