/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VettedPackagesChange : A change to the set of vetted packages.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VettedPackagesChange {
    #[serde(rename = "operation")]
    pub operation: Box<models::Operation>,
}

impl VettedPackagesChange {
    /// A change to the set of vetted packages.
    pub fn new(operation: models::Operation) -> VettedPackagesChange {
        VettedPackagesChange {
            operation: Box::new(operation),
        }
    }
}

