/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.5.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VettedPackage : A package that is vetting on a given participant and synchronizer, modelled after ``VettedPackage`` in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_, enriched with the package name and version.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VettedPackage {
    /// Package ID of this package. Always present.
    #[serde(rename = "packageId")]
    pub package_id: String,
    /// The time from which this package is vetted. Empty if vetting time has no lower bound.
    #[serde(rename = "validFromInclusive", skip_serializing_if = "Option::is_none")]
    pub valid_from_inclusive: Option<String>,
    /// The time until which this package is vetted. Empty if vetting time has no upper bound.
    #[serde(rename = "validUntilExclusive", skip_serializing_if = "Option::is_none")]
    pub valid_until_exclusive: Option<String>,
    /// Name of this package. Only available if the package has been uploaded to the current participant. If unavailable, is empty string.
    #[serde(rename = "packageName")]
    pub package_name: String,
    /// Version of this package. Only available if the package has been uploaded to the current participant. If unavailable, is empty string.
    #[serde(rename = "packageVersion")]
    pub package_version: String,
}

impl VettedPackage {
    /// A package that is vetting on a given participant and synchronizer, modelled after ``VettedPackage`` in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_, enriched with the package name and version.
    pub fn new(package_id: String, package_name: String, package_version: String) -> VettedPackage {
        VettedPackage {
            package_id,
            valid_from_inclusive: None,
            valid_until_exclusive: None,
            package_name,
            package_version,
        }
    }
}

