[package]
name = "commitment"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"        
authors = ["DFST"]      

[dependencies]

[addresses]
commitment = "0x0"

[dev-dependencies]

[dev-addresses]


