/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialClaim {
    /// The property of the claim
    #[serde(rename = "property")]
    pub property: String,
    /// The value of the claim
    #[serde(rename = "value")]
    pub value: String,
}

impl CredentialClaim {
    pub fn new(property: String, value: String) -> CredentialClaim {
        CredentialClaim {
            property,
            value,
        }
    }
}

