/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisclosedContract {
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "contractId")]
    pub contract_id: String,
    #[serde(rename = "templateId")]
    pub template_id: String,
    #[serde(rename = "domainId", skip_serializing_if = "Option::is_none")]
    pub domain_id: Option<String>,
    /// The base64 encoded created event blob
    #[serde(rename = "createdEventBlob")]
    pub created_event_blob: String,
}

impl DisclosedContract {
    pub fn new(contract_id: String, template_id: String, created_event_blob: String) -> DisclosedContract {
        DisclosedContract {
            created_at: None,
            contract_id,
            template_id,
            domain_id: None,
            created_event_blob,
        }
    }
}

