/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Error : A problem occurred with processing the request. For instance: syntactically invalid JSON body, missing required fields, etc.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// An error code, e.g. invalid_token
    #[serde(rename = "error")]
    pub error: String,
    /// A description of the error
    #[serde(rename = "error_description")]
    pub error_description: String,
}

impl Error {
    /// A problem occurred with processing the request. For instance: syntactically invalid JSON body, missing required fields, etc.
    pub fn new(error: String, error_description: String) -> Error {
        Error {
            error,
            error_description,
        }
    }
}

