/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetInstrumentConfigurationRequest {
    /// The registrar party id
    #[serde(rename = "registrar")]
    pub registrar: String,
    #[serde(rename = "instrumentIdentifier")]
    pub instrument_identifier: Box<models::InstrumentIdentifier>,
}

impl GetInstrumentConfigurationRequest {
    pub fn new(registrar: String, instrument_identifier: models::InstrumentIdentifier) -> GetInstrumentConfigurationRequest {
        GetInstrumentConfigurationRequest {
            registrar,
            instrument_identifier: Box::new(instrument_identifier),
        }
    }
}

