/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAllPackagesResponse {
    #[serde(rename = "packages")]
    pub packages: Vec<models::PackageDescriptor>,
}

impl GetAllPackagesResponse {
    pub fn new(packages: Vec<models::PackageDescriptor>) -> GetAllPackagesResponse {
        GetAllPackagesResponse {
            packages,
        }
    }
}

