/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFactoryRequest {
    /// The arguments that are intended to be passed to the choice provided by the factory. To avoid repeating the Daml type definitions, they are specified as JSON objects. However the concrete format is given by how the choice arguments are encoded using the Daml JSON API  The choice arguments are provided so that the registry can also provide choice-argument specific contracts, e.g., the configuration for a specific instrument-id. 
    #[serde(rename = "choiceArguments")]
    pub choice_arguments: serde_json::Value,
}

impl GetFactoryRequest {
    pub fn new(choice_arguments: serde_json::Value) -> GetFactoryRequest {
        GetFactoryRequest {
            choice_arguments,
        }
    }
}

