/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstrumentId : The identifier of the instrument.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentId {
    /// The party administering the instrument.
    #[serde(rename = "admin")]
    pub admin: String,
    /// The unique identifier of the instrument.
    #[serde(rename = "id")]
    pub id: String,
}

impl InstrumentId {
    /// The identifier of the instrument.
    pub fn new(admin: String, id: String) -> InstrumentId {
        InstrumentId {
            admin,
            id,
        }
    }
}

