/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstrumentConfigurationPayload {
    /// The operator party id
    #[serde(rename = "operator")]
    pub operator: String,
    /// The provider party id
    #[serde(rename = "provider")]
    pub provider: String,
    /// The registrar party id
    #[serde(rename = "registrar")]
    pub registrar: String,
    #[serde(rename = "defaultIdentifier")]
    pub default_identifier: Box<models::InstrumentIdentifier>,
    /// Additional instrument identifiers
    #[serde(rename = "additionalIdentifiers")]
    pub additional_identifiers: Vec<models::InstrumentIdentifier>,
    /// Credential requirements to mint/burn a given asset
    #[serde(rename = "issuerRequirements")]
    pub issuer_requirements: Vec<models::PartyCredentialRequirement>,
    /// Credential requirements to transfer/lock/unlock a given asset
    #[serde(rename = "holderRequirements")]
    pub holder_requirements: Vec<models::PartyCredentialRequirement>,
}

impl InstrumentConfigurationPayload {
    pub fn new(operator: String, provider: String, registrar: String, default_identifier: models::InstrumentIdentifier, additional_identifiers: Vec<models::InstrumentIdentifier>, issuer_requirements: Vec<models::PartyCredentialRequirement>, holder_requirements: Vec<models::PartyCredentialRequirement>) -> InstrumentConfigurationPayload {
        InstrumentConfigurationPayload {
            operator,
            provider,
            registrar,
            default_identifier: Box::new(default_identifier),
            additional_identifiers,
            issuer_requirements,
            holder_requirements,
        }
    }
}

