/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OfferBurnRequest : The request to get the factory and choice context for creating a burn offer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfferBurnRequest {
    /// The party whose holding will be burned.
    #[serde(rename = "holder")]
    pub holder: String,
    #[serde(rename = "instrumentId")]
    pub instrument_id: Box<models::InstrumentId>,
}

impl OfferBurnRequest {
    /// The request to get the factory and choice context for creating a burn offer.
    pub fn new(holder: String, instrument_id: models::InstrumentId) -> OfferBurnRequest {
        OfferBurnRequest {
            holder,
            instrument_id: Box::new(instrument_id),
        }
    }
}

