/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PackageDescriptor : Contains the package ids for a given package name
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageDescriptor {
    /// Name of the package
    #[serde(rename = "name")]
    pub name: String,
    /// Package ID
    #[serde(rename = "id")]
    pub id: String,
}

impl PackageDescriptor {
    /// Contains the package ids for a given package name
    pub fn new(name: String, id: String) -> PackageDescriptor {
        PackageDescriptor {
            name,
            id,
        }
    }
}

