/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartyCredentialRequirement {
    /// Required issuer of the credential
    #[serde(rename = "issuer")]
    pub issuer: String,
    /// Required (property, value) pairs that the holder has to have claims for as a subject
    #[serde(rename = "requiredClaims")]
    pub required_claims: Vec<models::CredentialClaim>,
}

impl PartyCredentialRequirement {
    pub fn new(issuer: String, required_claims: Vec<models::CredentialClaim>) -> PartyCredentialRequirement {
        PartyCredentialRequirement {
            issuer,
            required_claims,
        }
    }
}

