/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestMintRequest : The request to get the factory and choice context for creating a mint request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestMintRequest {
    /// The party for whom the holding will be minted.
    #[serde(rename = "holder")]
    pub holder: String,
    #[serde(rename = "instrumentId")]
    pub instrument_id: Box<models::InstrumentId>,
}

impl RequestMintRequest {
    /// The request to get the factory and choice context for creating a mint request.
    pub fn new(holder: String, instrument_id: models::InstrumentId) -> RequestMintRequest {
        RequestMintRequest {
            holder,
            instrument_id: Box::new(instrument_id),
        }
    }
}

