/*
 * Utilities API
 *
 * Exposes technical information and contract data of the Utility App
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RequestBurnRequest : The request to get the factory and choice context for creating a burn request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestBurnRequest {
    /// The party whose holding will be burned.
    #[serde(rename = "holder")]
    pub holder: String,
    /// Contract ids of Holdings to be used for the burn.
    #[serde(rename = "holdingContractIds")]
    pub holding_contract_ids: Vec<String>,
    #[serde(rename = "instrumentId")]
    pub instrument_id: Box<models::InstrumentId>,
}

impl RequestBurnRequest {
    /// The request to get the factory and choice context for creating a burn request.
    pub fn new(holder: String, holding_contract_ids: Vec<String>, instrument_id: models::InstrumentId) -> RequestBurnRequest {
        RequestBurnRequest {
            holder,
            holding_contract_ids,
            instrument_id: Box::new(instrument_id),
        }
    }
}

