[package]
name = "proto"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tonic = { workspace = true, features = ["tls-webpki-roots"] }
tonic-reflection.workspace = true
tonic-prost.workspace = true
prost.workspace = true
prost-types.workspace = true
prost-reflect.workspace = true
prost-reflect-build.workspace = true
once_cell.workspace = true
# Event buffering
buffer = { path = "../buffer" }

[build-dependencies]
tonic-reflection.workspace = true
tonic-build.workspace = true
tonic-prost-build.workspace = true
prost-build.workspace = true
prost-reflect.workspace = true
prost-reflect-build.workspace = true
once_cell.workspace = true
