[package]
name = "proto"
version = "0.1.0"
edition = "2024"
authors = ["DFST"]
license = "Apache-2.0"

[dependencies]
tonic = { version = "0.13", features = ["tls-webpki-roots"] }
prost = "0.13"
prost-types = "0.13"

[build-dependencies]
tonic-build = "0.13"
prost-build = "0.13"
