[package]
name = "add"
version = "0.1.0"
edition = "2024.beta" 
license = "Apache 2.0"   

[dependencies]
commitment = { git = "https://github.com/SilvanaOne/silvana", rev = "c45399d92bc3bc5320a0c019248bd0b12c10039f", subdir = "move/commitment" }
coordination = { git = "https://github.com/SilvanaOne/silvana", rev = "c45399d92bc3bc5320a0c019248bd0b12c10039f",  subdir = "move/coordination" }

[addresses]
add = "0x0"

[dev-dependencies]

[dev-addresses]


