/*
 * allocation off-ledger API
 *
 * Implemented by token registries for the purpose of the use and management of allocations by wallets and apps orchestrating the settlement of asset transfers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChoiceContext : The context required to exercise a choice on a contract via an interface. Used to retrieve additional reference date that is passed in via disclosed contracts, which are in turn referred to via their contract ID in the `choiceContextData`. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChoiceContext {
    /// The additional data to use when exercising the choice.
    #[serde(rename = "choiceContextData")]
    pub choice_context_data: serde_json::Value,
    /// The contracts that are required to be disclosed to the participant node for exercising the choice. 
    #[serde(rename = "disclosedContracts")]
    pub disclosed_contracts: Vec<models::DisclosedContract>,
}

impl ChoiceContext {
    /// The context required to exercise a choice on a contract via an interface. Used to retrieve additional reference date that is passed in via disclosed contracts, which are in turn referred to via their contract ID in the `choiceContextData`. 
    pub fn new(choice_context_data: serde_json::Value, disclosed_contracts: Vec<models::DisclosedContract>) -> ChoiceContext {
        ChoiceContext {
            choice_context_data,
            disclosed_contracts,
        }
    }
}

