/*
 * allocation off-ledger API
 *
 * Implemented by token registries for the purpose of the use and management of allocations by wallets and apps orchestrating the settlement of asset transfers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "error")]
    pub error: String,
}

impl ErrorResponse {
    pub fn new(error: String) -> ErrorResponse {
        ErrorResponse {
            error,
        }
    }
}

