/*
 * allocation off-ledger API
 *
 * Implemented by token registries for the purpose of the use and management of allocations by wallets and apps orchestrating the settlement of asset transfers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetChoiceContextRequest : A request to get the context for executing a choice on a contract. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetChoiceContextRequest {
    /// Metadata that will be passed to the choice, and should be incorporated into the choice context. Provided for extensibility. 
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<std::collections::HashMap<String, String>>,
}

impl GetChoiceContextRequest {
    /// A request to get the context for executing a choice on a contract. 
    pub fn new() -> GetChoiceContextRequest {
        GetChoiceContextRequest {
            meta: None,
        }
    }
}

