// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file silvana/options/v1/options.proto (package silvana.options.v1, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file silvana/options/v1/options.proto.
 */
export const file_silvana_options_v1_options: GenFile = /*@__PURE__*/
  fileDesc("CiBzaWx2YW5hL29wdGlvbnMvdjEvb3B0aW9ucy5wcm90bxISc2lsdmFuYS5vcHRpb25zLnYxOj0KCXNlcXVlbmNlcxIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY/rEDIAEoCFIJc2VxdWVuY2VzOjcKBnNlYXJjaBIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY/7EDIAEoCFIGc2VhcmNoQj9aPWdpdGh1Yi5jb20vU2lsdmFuYU9uZS96ay10ZXN0cy9wYWNrYWdlcy9hdnMvcnBjL3Byb3RvO29wdGlvbnNiBnByb3RvMw", [file_google_protobuf_descriptor]);

/**
 * @generated from extension: bool sequences = 55550;
 */
export const sequences: GenExtension<FieldOptions, boolean> = /*@__PURE__*/
  extDesc(file_silvana_options_v1_options, 0);

/**
 * @generated from extension: bool search = 55551;
 */
export const search: GenExtension<FieldOptions, boolean> = /*@__PURE__*/
  extDesc(file_silvana_options_v1_options, 1);

