/*
 * transfer instruction off-ledger API
 *
 * Implemented by token registries for the purpose of supporting the initiation of asset transfers; e.g. to settle off-ledger obligations. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFactoryRequest {
    /// The arguments that are intended to be passed to the choice provided by the factory. To avoid repeating the Daml type definitions, they are specified as JSON objects. However the concrete format is given by how the choice arguments are encoded using the Daml JSON API (with the `extraArgs.context` and `extraArgs.meta` fields set to the empty object).  The choice arguments are provided so that the registry can also provide choice-argument specific contracts, e.g., the configuration for a specific instrument-id. 
    #[serde(rename = "choiceArguments")]
    pub choice_arguments: serde_json::Value,
    /// If set to true, the response will not include debug fields.
    #[serde(rename = "excludeDebugFields", skip_serializing_if = "Option::is_none")]
    pub exclude_debug_fields: Option<bool>,
}

impl GetFactoryRequest {
    pub fn new(choice_arguments: serde_json::Value) -> GetFactoryRequest {
        GetFactoryRequest {
            choice_arguments,
            exclude_debug_fields: None,
        }
    }
}

