/*
 * transfer instruction off-ledger API
 *
 * Implemented by token registries for the purpose of supporting the initiation of asset transfers; e.g. to settle off-ledger obligations. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransferFactoryWithChoiceContext : The transfer factory contract together with the choice context required to exercise the choice provided by the factory. Typically used to implement the generic initiation of on-ledger workflows via a Daml interface.  Clients SHOULD avoid reusing the same `FactoryWithChoiceContext` for exercising multiple choices, as the choice context MAY be specific to the choice being exercised. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransferFactoryWithChoiceContext {
    /// The contract ID of the contract implementing the factory interface.
    #[serde(rename = "factoryId")]
    pub factory_id: String,
    /// The kind of transfer workflow that will be used: * `offer`: offer a transfer to the receiver and only transfer if they accept * `direct`: transfer directly to the receiver without asking them for approval.   Only chosen if the receiver has pre-approved direct transfers. * `self`: a self-transfer where the sender and receiver are the same party.   No approval is required, and the transfer is typically immediate. 
    #[serde(rename = "transferKind")]
    pub transfer_kind: TransferKind,
    #[serde(rename = "choiceContext")]
    pub choice_context: Box<models::ChoiceContext>,
}

impl TransferFactoryWithChoiceContext {
    /// The transfer factory contract together with the choice context required to exercise the choice provided by the factory. Typically used to implement the generic initiation of on-ledger workflows via a Daml interface.  Clients SHOULD avoid reusing the same `FactoryWithChoiceContext` for exercising multiple choices, as the choice context MAY be specific to the choice being exercised. 
    pub fn new(factory_id: String, transfer_kind: TransferKind, choice_context: models::ChoiceContext) -> TransferFactoryWithChoiceContext {
        TransferFactoryWithChoiceContext {
            factory_id,
            transfer_kind,
            choice_context: Box::new(choice_context),
        }
    }
}
/// The kind of transfer workflow that will be used: * `offer`: offer a transfer to the receiver and only transfer if they accept * `direct`: transfer directly to the receiver without asking them for approval.   Only chosen if the receiver has pre-approved direct transfers. * `self`: a self-transfer where the sender and receiver are the same party.   No approval is required, and the transfer is typically immediate. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransferKind {
    #[serde(rename = "self")]
    VariantSelf,
    #[serde(rename = "direct")]
    Direct,
    #[serde(rename = "offer")]
    Offer,
}

impl Default for TransferKind {
    fn default() -> TransferKind {
        Self::VariantSelf
    }
}

