/*
 * token metadata service
 *
 * Implemented by token registries for the purpose of serving metadata about their tokens and the standards supported by the registry. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRegistryInfoResponse {
    /// The Daml party representing the registry app
    #[serde(rename = "adminId")]
    pub admin_id: String,
    /// Map from token standard API name to the minor version of the API supported, e.g., splice-api-token-metadata-v1 -> 1 where the `1` corresponds to the minor version. 
    #[serde(rename = "supportedApis")]
    pub supported_apis: std::collections::HashMap<String, i32>,
}

impl GetRegistryInfoResponse {
    pub fn new(admin_id: String, supported_apis: std::collections::HashMap<String, i32>) -> GetRegistryInfoResponse {
        GetRegistryInfoResponse {
            admin_id,
            supported_apis,
        }
    }
}

