/*
 * token metadata service
 *
 * Implemented by token registries for the purpose of serving metadata about their tokens and the standards supported by the registry. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Instrument {
    /// The unique identifier assigned by the admin to the instrument.
    #[serde(rename = "id")]
    pub id: String,
    /// The display name for the instrument recommended by the instrument admin. This is not necessarily unique.
    #[serde(rename = "name")]
    pub name: String,
    /// The symbol for the instrument recommended by the instrument admin. This is not necessarily unique.
    #[serde(rename = "symbol")]
    pub symbol: String,
    /// Decimal encoded current total supply of the instrument.
    #[serde(rename = "totalSupply", skip_serializing_if = "Option::is_none")]
    pub total_supply: Option<String>,
    /// The timestamp when the total supply was last computed.
    #[serde(rename = "totalSupplyAsOf", skip_serializing_if = "Option::is_none")]
    pub total_supply_as_of: Option<String>,
    /// The number of decimal places used by the instrument.  Must be a number between 0 and 10, as the Daml interfaces represent holding amounts as `Decimal` values, which use 10 decimal places and are precise for 38 digits. Setting this to 0 means that the instrument can only be held in whole units.  This number SHOULD be used for display purposes in a wallet to decide how many decimal places to show and accept when displaying or entering amounts. 
    #[serde(rename = "decimals")]
    pub decimals: i32,
    /// Map from token standard API name to the minor version of the API supported, e.g., splice-api-token-metadata-v1 -> 1 where the `1` corresponds to the minor version. 
    #[serde(rename = "supportedApis")]
    pub supported_apis: std::collections::HashMap<String, i32>,
}

impl Instrument {
    pub fn new(id: String, name: String, symbol: String, decimals: i32, supported_apis: std::collections::HashMap<String, i32>) -> Instrument {
        Instrument {
            id,
            name,
            symbol,
            total_supply: None,
            total_supply_as_of: None,
            decimals,
            supported_apis,
        }
    }
}

